<?php
/**
 * N Framework
 *
 * WARNING: This file is part of the core N Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @since      0.0.1
 * @package    N
 * @subpackage N/lib/admin/import
 */

if (!defined('ABSPATH')):
	exit; // Exit if accessed directly.
endif;

/**
 * Sim API importer with ajax
 *
 * @since 0.0.1
 */
function _n_ajax_sim_api_importer(){
	$page                      = isset($_POST['page']) ? intval($_POST['page']) : 1;
	$loai_sim                  = isset($_POST['loai_sim']) ? strval($_POST['loai_sim']) : 1;
	$api_gia_tra_truoc         = isset($_POST['api_gia_tra_truoc']) ? intval($_POST['api_gia_tra_truoc']) : 0;
	$api_gia_tra_truoc_kem_goi = isset($_POST['api_gia_tra_truoc_kem_goi']) ? intval($_POST['api_gia_tra_truoc_kem_goi']) : 0;
	$api_gia_tra_sau           = isset($_POST['api_gia_tra_sau']) ? intval($_POST['api_gia_tra_sau']) : 0;
	$task                      = isset($_POST['task']) ? strval($_POST['task']) : '';
	$count                     = isset($_POST['count']) ? intval($_POST['count']) : 0;
	$response                  = [];
	$imported_data             = [];
	$status                    = 'complete';

	if ($task == 'price_sync'):
		update_option('_api_gia_tra_truoc', $api_gia_tra_truoc);
		update_option('_api_gia_tra_truoc_kem_goi', $api_gia_tra_truoc_kem_goi);
		update_option('_api_gia_tra_sau', $api_gia_tra_sau);

		$response = [
			'status' => 'continue',
			'count'  => 0,
			'task'   => 'sim_import',
			'page'   => 0,
		];

		wp_send_json_success($response);
	endif;

	$response = _n_api_filter_msisdn([
		"types"      => [$loai_sim],
		"regions"    => [0, 2],
		"sizeOfPage" => 100,
		"statuss"    => [0, 1],
		"page"       => $page,
	]);

	$items           = $response->data->items;
	$number_per_page = $response->data->numberPerPage;
	$code            = $response->code;
	$price           = '';

	if ($loai_sim == 0):
		$price = get_option('_api_gia_tra_truoc');
	elseif ($loai_sim == 1):
		$price = get_option('_api_gia_tra_sau');
	elseif ($loai_sim == 2):
		$price = get_option('_api_gia_tra_truoc_kem_goi');
	endif;

	if ($code == 1):
		$status = 'continue';
		if (!empty($items)):

			if (!function_exists('post_exists')):
				require_once(ABSPATH . 'wp-admin/includes/post.php');
			endif;

			foreach ($items as $item):
				wp_send_json_success($item);
				// Hết hàng thì xoá, còn thì update giá
				$product_id    = post_exists($item->msisdn, '', '', 'product');
				$msisdn_detail = _n_api_msisdn_detail($item->msisdn);

				if ($product_id):
					if ($msisdn_detail->code == 1):
						if ($msisdn_detail->data->items[0]->statusStr != 'Trong kho'):
							_n_delete_product_by_id($product_id);
						else:
							update_post_meta($product_id, '_price', $price);
						endif;
					else:
						_n_delete_product_by_id($product_id);
					endif;
					continue;
				endif;

				// Nếu sim hết hàng thì bỏ qua
				if ($msisdn_detail->code == 1 && $msisdn_detail->data->items[0]->statusStr != 'Trong kho'):
					continue;
				endif;

				if ($item->typeStr == 'Trả trước'):
					$loai_sim = '_tra_truoc';
				else:
					$loai_sim = '_tra_sau';
				endif;

				$product_data = [
					'type'         => 'sim',
					'title'        => $item->msisdn,
					'phone'        => $item->msisdn,
					'price'        => $price,
					'cost'         => '',
					'goi_cuoc'     => '',
					'loai_sim'     => $loai_sim,
					'nha_mang'     => _n_check_nha_mang($item->msisdn),
					'nha_cung_cap' => '_kho_chon_so',
				];

				$product_id = _n_create_product($product_data);

				if ($product_id):
					array_push($imported_data, $item->msisdn);
				endif;
			endforeach;
		else:
			$status = 'complete';
		endif;
	else:
		$status = 'complete';
	endif;

	$count += count($imported_data);

	$response = [
		'imported_data'   => $imported_data,
		'status'          => $status,
		'task'            => 'sim_import',
		'count'           => $count,
		'page'            => $response->data->pageNumber,
		'number_per_page' => $number_per_page,
	];

	wp_send_json_success($response);
	wp_die();
}

add_action('wp_ajax_api_import_sim', '_n_ajax_sim_api_importer');
