<?php
/**
 * N Framework
 *
 * WARNING: This file is part of the core N Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @since      0.0.1
 * @package    N
 * @subpackage N/lib/admin/import
 */

if (!defined('ABSPATH')):
	exit; // Exit if accessed directly.
endif;

use Shuchkin\SimpleXLSX;

/**
 * Sim importer with ajax
 *
 * @since 0.0.1
 */
function _n_ajax_package_importer(){
	if (!(is_array($_POST) && is_array($_FILES) && defined('DOING_AJAX') && DOING_AJAX)):
		wp_send_json_error('Lỗi');
	endif;

	$file          = $_FILES['file'] ?? null;
	$start_row     = isset($_POST['start_row']) ? intval($_POST['start_row']) : 1;
	$history       = isset($_POST['history']) ? intval($_POST['history']) : 0;
	$loai_sim      = isset($_POST['loai_sim']) ? strval($_POST['loai_sim']) : '';
	$batch_size    = 100;
	$end_row       = $start_row + $batch_size - 1;
	$imported_data = [];
	$status        = 'complete';

	if ($xlsx = SimpleXLSX::parse($file['tmp_name']) && $xlsx_rows = SimpleXLSX::parse($file['tmp_name'])->rows()):
		$count = count($xlsx_rows) - 1;

		if ($history == 0):
			$args = [
				'post_type'   => 'import_history',
				'post_status' => 'publish',
			];

			$import_history_id = wp_insert_post($args);

			if (!is_wp_error($import_history_id)):
				update_post_meta($import_history_id, '_file_name', $file['name']);
				$history = $import_history_id;
			endif;
		endif;

		if ($start_row <= $count):
			$status = 'continue';
		endif;

		if (!function_exists('post_exists')):
			require_once(ABSPATH . 'wp-admin/includes/post.php');
		endif;

		for ($row = $start_row; $row <= $end_row; $row ++):
			if ($row == 0):
				continue;
			endif;

			if (isset($xlsx_rows[$row])):
				$item = $xlsx_rows[$row];

				$product_name    = $item[0];
				$product_price   = $item[1];
				$product_content = $item[2];
				$package_cam_ket = $item[3];

				$product_data = [
					'type'     => 'package',
					'title'    => $product_name,
					'content'  => $product_content,
					'price'    => $product_price,
					'cam_ket'  => $package_cam_ket,
					'loai_sim' => $loai_sim,
				];

				$product_id = _n_create_package($product_data);

				if ($product_id):
					array_push($imported_data, $product_name);
				endif;

			else:
				$status = 'complete';
				break;
			endif;
		endfor;
	endif;

	$response = [
		'imported_data' => $imported_data,
		'end_row'       => $end_row,
		'history'       => $history,
		'status'        => $status
	];

	wp_send_json_success($response);
	wp_die();
}

add_action('wp_ajax_package_importer', '_n_ajax_package_importer');
