<?php
/**
 * N Framework
 *
 * WARNING: This file is part of the core N Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @since      0.0.1
 * @package    N
 * @subpackage N/lib/admin/import
 */

if (!defined('ABSPATH')):
	exit; // Exit if accessed directly.
endif;

use Shuchkin\SimpleXLSX;

/**
 * Sim importer with ajax
 *
 * @since 0.0.1
 */
function _n_ajax_sim_importer(){
	if (!(is_array($_POST) && is_array($_FILES) && defined('DOING_AJAX') && DOING_AJAX)):
		wp_send_json_error('Lỗi');
	endif;

	$file                               = $_FILES['file'] ?? null;
	$start_row                          = isset($_POST['start_row']) ? intval($_POST['start_row']) : 1;
	$history                            = isset($_POST['history']) ? intval($_POST['history']) : 0;
	$loai_sim                           = isset($_POST['loai_sim']) ? strval($_POST['loai_sim']) : '';
	$dang_sim                           = isset($_POST['dang_sim']) ? strval($_POST['dang_sim']) : '';
	$nha_mang                           = isset($_POST['nha_mang']) ? strval($_POST['nha_mang']) : '';
	$nha_cung_cap                       = isset($_POST['nha_cung_cap']) ? strval($_POST['nha_cung_cap']) : '';
	$gia                                = isset($_POST['gia']) ? intval($_POST['gia']) : 0;
	$dang_file                          = isset($_POST['dang_file']) ? strval($_POST['dang_file']) : '';
	$chiet_khau_toan_file               = isset($_POST['chiet_khau_toan_file']) ? intval($_POST['chiet_khau_toan_file']) : 0;
	$chiet_khau_toan_file_truc_tiep     = isset($_POST['chiet_khau_toan_file_truc_tiep']) ? intval($_POST['chiet_khau_toan_file_truc_tiep']) : 0;
	$chiet_khau_theo_khoang_gia_gia_tu  = $_POST['chiet_khau_theo_khoang_gia_gia_tu'] ?? [];
	$chiet_khau_theo_khoang_gia_gia_den = $_POST['chiet_khau_theo_khoang_gia_gia_den'] ?? [];
	$chiet_khau_theo_khoang_gia         = $_POST['chiet_khau_theo_khoang_gia'] ?? [];
	$batch_size                         = 100;
	$end_row                            = $start_row + $batch_size - 1;
	$response                           = [];
	$imported_data                      = [];
	$status                             = 'complete';
	$cost                               = 0;
	$price                              = 0;
	$phone                              = '';
	$title                              = '';
	$goi_cuoc                           = '';
	$chiet_khau_theo_khoang_gia_args    = [];

	if ($xlsx = SimpleXLSX::parse($file['tmp_name']) && $xlsx_rows = SimpleXLSX::parse($file['tmp_name'])->rows()):
		$count = count($xlsx_rows) - 1;

		if ($history == 0):
			$args = [
				'post_type'   => 'import_history',
				'post_status' => 'publish',
			];

			$import_history_id = wp_insert_post($args);

			if (!is_wp_error($import_history_id)):
				update_post_meta($import_history_id, '_file_name', $file['name']);
				$history = $import_history_id;
			endif;
		endif;

		if ($start_row <= $count):
			$status = 'continue';
		endif;

		if (!empty($chiet_khau_theo_khoang_gia_gia_tu)):
			foreach ($chiet_khau_theo_khoang_gia_gia_tu as $key => $item):
				$chiet_khau_theo_khoang_gia_args[$key]['gia_tu'] = $item;
			endforeach;
		endif;

		if (!empty($chiet_khau_theo_khoang_gia_gia_den)):
			foreach ($chiet_khau_theo_khoang_gia_gia_den as $key => $item):
				$chiet_khau_theo_khoang_gia_args[$key]['gia_den'] = $item;
			endforeach;
		endif;

		if (!empty($chiet_khau_theo_khoang_gia)):
			foreach ($chiet_khau_theo_khoang_gia as $key => $item):
				$chiet_khau_theo_khoang_gia_args[$key]['chiet_khau'] = $item;
			endforeach;
		endif;

		if (!function_exists('post_exists')):
			require_once(ABSPATH . 'wp-admin/includes/post.php');
		endif;

		for ($row = $start_row; $row <= $end_row; $row ++):
			if ($row == 0):
				continue;
			endif;

			if (isset($xlsx_rows[$row])):
				$item = $xlsx_rows[$row];

				if ($dang_file == "dang_1"):
					$phone    = _n_complete_phone_number($item[1]);
					$title    = $phone;
					$goi_cuoc = $item[3];
					$price    = $gia;
				elseif ($dang_file == "dang_2"):
					$phone    = _n_complete_phone_number($item[1]);
					$title    = $item[2];
					$price    = $item[3];
					$cost     = $item[4];
					$goi_cuoc = $item[5];
				endif;

				$product_data = [
					'type'         => 'sim',
					'title'        => $title,
					'phone'        => $phone,
					'price'        => $price,
					'cost'         => $cost,
					'goi_cuoc'     => $goi_cuoc,
					'loai_sim'     => $loai_sim,
					'nha_mang'     => $nha_mang,
					'nha_cung_cap' => $nha_cung_cap,
				];

				$product_id = _n_create_product($product_data);

				if ($product_id):
					array_push($imported_data, $phone);
					update_post_meta($product_id, '_import_history', $history);
					update_post_meta($product_id, '_chiet_khau', $chiet_khau_toan_file);
					update_post_meta($product_id, '_chiet_khau_vnd', $chiet_khau_toan_file_truc_tiep);
					update_post_meta($product_id, '_chiet_khau_theo_khoang_gia', $chiet_khau_theo_khoang_gia_args);

					if ($dang_sim == 'sim_top'):
						update_post_meta($product_id, '_sim_top', 'yes');
					endif;

					if ($dang_sim == 'sim_livestream'):
						update_post_meta($product_id, '_sim_livestream', 'yes');
					endif;

					if ($dang_sim == 'sim_tang'):
						update_post_meta($product_id, '_sim_tang', 'yes');
					endif;
				endif;
			else:
				$status = 'complete';
				break;
			endif;
		endfor;
	endif;

	$response = [
		'imported_data' => $imported_data,
		'end_row'       => $end_row,
		'history'       => $history,
		'status'        => $status
	];

	wp_send_json_success($response);
	wp_die();
}

add_action('wp_ajax_sim_importer', '_n_ajax_sim_importer');
