<?php
/**
 * N Framework
 *
 * WARNING: This file is part of the core N Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @since      0.0.1
 * @package    N
 * @subpackage N/lib/admin/import
 */

if (!defined('ABSPATH')):
	exit; // Exit if accessed directly.
endif;

use Shuchkin\SimpleXLSX;

/**
 * Sim super data importer with ajax
 *
 * @since 0.0.1
 */
function _n_ajax_sim_super_data_importer(){
	if (!(is_array($_POST) && is_array($_FILES) && defined('DOING_AJAX') && DOING_AJAX)):
		wp_send_json_error('Lỗi');
	endif;

	$file          = $_FILES['file'] ?? null;
	$start_row     = isset($_POST['start_row']) ? intval($_POST['start_row']) : 1;
	$history       = isset($_POST['history']) ? intval($_POST['history']) : 0;
	$nha_mang      = isset($_POST['nha_mang']) ? strval($_POST['nha_mang']) : '';
	$nha_cung_cap  = isset($_POST['nha_cung_cap']) ? strval($_POST['nha_cung_cap']) : '';
	$batch_size    = 100;
	$end_row       = $start_row + $batch_size - 1;
	$status        = 'complete';
	$cost          = 0;
	$price         = 0;
	$imported_data = [];

	if ($xlsx = SimpleXLSX::parse($file['tmp_name']) && $xlsx_rows = SimpleXLSX::parse($file['tmp_name'])->rows()):
		$count = count($xlsx_rows) - 1;

		if ($history == 0):
			$args = [
				'post_type'   => 'import_history',
				'post_status' => 'publish',
			];

			$import_history_id = wp_insert_post($args);

			if (!is_wp_error($import_history_id)):
				update_post_meta($import_history_id, '_file_name', $file['name']);
				$history = $import_history_id;
			endif;
		endif;

		if ($start_row <= $count):
			$status = 'continue';
		endif;

		if (!function_exists('post_exists')):
			require_once(ABSPATH . 'wp-admin/includes/post.php');
		endif;

		for ($row = $start_row; $row <= $end_row; $row ++):
			if ($row == 0):
				continue;
			endif;

			if (isset($xlsx_rows[$row])):
				$item = $xlsx_rows[$row];

				$title            = $item[0];
				$price            = $item[1];
				$cost             = $item[2];
				$chu_ky           = $item[3];
				$data             = $item[4];
				$thoai_noi_mang   = $item[5];
				$thoai_ngoai_mang = $item[6];
				$content          = $item[7];

				$product_data = [
					'type'         => 'sim_super_data',
					'title'        => $title,
					'content'      => $content,
					'phone'        => '',
					'price'        => $price,
					'cost'         => $cost,
					'goi_cuoc'     => '',
					'loai_sim'     => '',
					'nha_mang'     => $nha_mang,
					'nha_cung_cap' => $nha_cung_cap,
				];

				$product_id = _n_create_product($product_data);

				if ($product_id):
					array_push($imported_data, $title);
					update_post_meta($product_id, '_import_history', $history);
					update_post_meta($product_id, '_chu_ky', $chu_ky);
					update_post_meta($product_id, '_data', $data);
					update_post_meta($product_id, '_thoai_noi_mang', $thoai_noi_mang);
					update_post_meta($product_id, '_thoai_ngoai_mang', $thoai_ngoai_mang);
					update_post_meta($product_id, '_import_history', $history);
				endif;
			else:
				$status = 'complete';
				break;
			endif;
		endfor;
	endif;

	$response = [
		'imported_data' => $imported_data,
		'end_row'       => $end_row,
		'history'       => $history,
		'status'        => $status
	];

	wp_send_json_success($response);
	wp_die();
}

add_action('wp_ajax_sim_super_data_importer', '_n_ajax_sim_super_data_importer');
