<?php
/**
 * N Framework
 *
 * WARNING: This file is part of the core N Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @since      0.0.1
 * @package    N
 * @subpackage N/lib/admin/report
 */

if (!defined('ABSPATH')):
	exit; // Exit if accessed directly.
endif;

/**
 * Báo cáo sim
 */
function _n_get_sim_reports(){
	$date_start          = isset($_POST['date_start']) ? esc_attr($_POST['date_start']) : '';
	$date_end            = isset($_POST['date_end']) ? esc_attr($_POST['date_end']) : '';
	$nha_mang            = isset($_POST['nha_mang']) ? esc_attr($_POST['nha_mang']) : '';
	$loai_sim            = isset($_POST['loai_sim']) ? esc_attr($_POST['loai_sim']) : '';
	$nha_cung_cap        = isset($_POST['nha_cung_cap']) ? esc_attr($_POST['nha_cung_cap']) : '';
	$loai_sim_config     = _n_get_config('loai-sim');
	$nha_mang_config     = _n_get_config('nha-mang');
	$nha_cung_cap_config = _n_get_config('nha-cung-cap');
	$nha_mang_args       = [];
	$loai_sim_args       = [];
	$nha_cung_cap_args   = [];

	if ($nha_mang != ''):
		$nha_mang_args = [
			'key'   => '_nha_mang',
			'value' => $nha_mang,
		];
	endif;

	if ($loai_sim != ''):
		$loai_sim_args = [
			'key'   => '_loai_sim',
			'value' => $loai_sim,
		];
	endif;

	if ($nha_cung_cap != ''):
		$nha_cung_cap_args = [
			'key'   => '_nha_cung_cap',
			'value' => $nha_cung_cap,
		];
	endif;

	$args = [
		'post_type'      => 'shop_order',
		'posts_per_page' => - 1,
		'post_status'    => ['wc-completed'],
		'date_query'     => [
			[
				'after'     => $date_start,
				'before'    => $date_end,
				'inclusive' => true,
			],
		],
		'meta_query'     => [
			'relation' => 'AND',
			$nha_mang_args,
			$loai_sim_args,
			$nha_cung_cap_args,
		]
	];

	ob_start();
	$loop = new WP_Query($args);

	?>
	<table class="widefat striped" id="sim-report-table">
		<thead>
		<tr>
			<th scope="col">Số thuê bao</th>
			<th scope="col">Loại thuê bao</th>
			<th scope="col">Gói/Điểm</th>
			<th scope="col">Nhà mạng</th>
			<th scope="col">Giá bán</th>
			<th scope="col">Giá thu về</th>
			<th scope="col">Doanh thu</th>
			<th scope="col">Nhà cung cấp</th>
			<th scope="col">Cước tháng cam kết</th>
			<th scope="col">Thời gian cam kết</th>
			<th scope="col">Tên người đặt</th>
			<th scope="col">Địa chỉ</th>
			<th scope="col">Sđt</th>
		</tr>
		</thead>
		<tbody id="the-list">
		<?php
		$orders_total  = 0;
		$revenue_total = 0;
		if ($loop->have_posts()):
			while ($loop->have_posts()) : $loop->the_post();
				$order_id                = get_the_ID();
				$sim_id                  = get_post_meta($order_id, '_sim_id', true);
				$package_id              = get_post_meta($order_id, '_package_id', true);
				$order                   = wc_get_order($order_id);
				$gia_ban_html            = '';
				$gia_thu_ve_html         = '';
				$doanh_thu_html          = '';
				$cuoc_thang_cam_ket_html = '';
				$gia_ban                 = 0;

				if (!$sim_id):
					continue;
				endif;

				$product_type = get_post_meta($sim_id, '_type', true);

				if ($product_type == 'sim_super_data'):
					continue;
				endif;

				$orders_total = $orders_total + 1;
				$so_thue_bao  = get_post_meta($sim_id, '_phone_number', true);
				$goi          = get_post_meta($sim_id, '_package', true);
				$loai_sim     = get_post_meta($sim_id, '_loai_sim', true);
				$nha_mang     = get_post_meta($sim_id, '_nha_mang', true);
				$nha_cung_cap = get_post_meta($sim_id, '_nha_cung_cap', true);

				$order_items = $order->get_items();

				foreach ($order_items as $item_id => $item):
					if ($sim_id == $item->get_product_id()):
						$gia_ban      = $item->get_subtotal();
						$gia_ban_html = number_format($gia_ban) . "đ";
					endif;
				endforeach;

				$gia_thu_ve = get_post_meta($sim_id, '_cost', true);
				if ($gia_thu_ve > 0):
					$gia_thu_ve_html = number_format($gia_thu_ve) . "đ";
				else:
					$gia_thu_ve = 0;
				endif;

				if (is_numeric($gia_ban) && is_numeric($gia_thu_ve)):
					$doanh_thu      = $gia_ban - $gia_thu_ve;
					$revenue_total  += $doanh_thu;
					$doanh_thu_html = number_format($doanh_thu) . "đ";
				endif;

				$cuoc_thang_cam_ket = get_post_meta($sim_id, '_min_price', true);
				if ($cuoc_thang_cam_ket > 0):
					$cuoc_thang_cam_ket_html = number_format($cuoc_thang_cam_ket) . "đ";
				endif;

				$thoi_gian_cam_ket = get_post_meta($package_id, '_cam_ket', true);

				$ten_nguoi_dat = $order->get_billing_first_name();

				if ($order->get_billing_address_1() == '' && $order->get_billing_address_2() == '' && $order->get_billing_city() == '' && $order->get_billing_state() == ''):
					$dia_chi = get_post_meta($order_id, '_branch', true);
				else:
					$dia_chi = $order->get_billing_address_1() . ', ' . $order->get_billing_address_2() . ', ' . $order->get_billing_city() . ', ' . $order->get_billing_state();
				endif;

				$sdt = $order->get_billing_phone();
				?>
				<tr>
					<td><?= $so_thue_bao ?></td>
					<td><?= $loai_sim_config[$loai_sim]['name'] ?></td>
					<td><?= $goi ?></td>
					<td><?= $nha_mang_config[$nha_mang]['name'] ?></td>
					<td><?= $gia_ban_html ?></td>
					<td><?= $gia_thu_ve_html ?></td>
					<td><?= $doanh_thu_html ?></td>
					<td><?= $nha_cung_cap_config[$nha_cung_cap]['name'] ?></td>
					<td><?= $cuoc_thang_cam_ket_html ?></td>
					<td><?= $thoi_gian_cam_ket ?></td>
					<td><?= $ten_nguoi_dat ?></td>
					<td><?= $dia_chi ?></td>
					<td><?= $sdt ?></td>
				</tr>
			<?php endwhile;
			wp_reset_postdata();
		else: ?>
			<tr>
				<td colspan="13">Không có dữ liệu</td>
			</tr>
		<?php endif; ?>
		</tbody>
	</table>
	<div class="total-report">
		<p class="orders-total">Tổng: <?= $orders_total ?></p>
		<p class="revenue-total">Tổng doanh thu: <?= number_format($revenue_total) . 'đ' ?></p>
	</div>
	<div class="export-wrapper">
		<button id="exportBtn" class="button">Export to Excel</button>
	</div>
	<?php

	$result = ob_get_clean();
	wp_send_json_success($result);

	wp_die();
}

add_action('wp_ajax_sim_report', '_n_get_sim_reports');
