<?php
/**
 * N Framework
 *
 * WARNING: This file is part of the core N Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @since      0.0.1
 * @package    N
 * @subpackage N/config
 */

if (!defined('ABSPATH')):
	exit; // Exit if accessed directly.
endif;

return [
	"AxAAyA"   => "AxA.AyA",
	"AxBAyB"   => "AxB.AyB",
	"AxAyAz"   => "Ax.Ay.Az",
	"AxBxCx"   => "Ax.Bx.Cx",
	"ABxABy"   => "ABx.ABy",
	"xAByAB"   => "xAB.yAB",
	"AxAByB"   => "AxA.ByB",
	"AxABxB"   => "AxA.BxB",
	"AAxBBy"   => "AAx.BBy",
	"xAAyBB"   => "xAA.yBB",
	"xABABy"   => "xAB.ABy",
	"ABxyAB"   => "AB.xy.AB",
	"ABABAx"   => "AB.AB.Ax",
	"ABABxB"   => "AB.AB.xB",
	"ABABxy"   => "AB.AB.xy",
	"AxABBy"   => "AxA.BBy",
	"xAAByB"   => "xA.AB.yB",
	"AxxyBy"   => "Ax.xy.By",
	"ABCxABCy" => "ABCx.ABCy",
];
