<?php
return [
	["name" => "Quận Ba Đình", "code" => "001", "parent_code" => "01"],
	["name" => "Quận Hoàn Kiếm", "code" => "002", "parent_code" => "01"],
	["name" => "Quận Tây Hồ", "code" => "003", "parent_code" => "01"],
	["name" => "Quận Long Biên", "code" => "004", "parent_code" => "01"],
	["name" => "Quận Cầu Giấy", "code" => "005", "parent_code" => "01"],
	["name" => "Quận Đống Đa", "code" => "006", "parent_code" => "01"],
	["name" => "Quận Hai Bà Trưng", "code" => "007", "parent_code" => "01"],
	["name" => "Quận Hoàng Mai", "code" => "008", "parent_code" => "01"],
	["name" => "Quận Thanh Xuân", "code" => "009", "parent_code" => "01"],
	["name" => "Huyện Sóc Sơn", "code" => "016", "parent_code" => "01"],
	["name" => "Huyện Đông Anh", "code" => "017", "parent_code" => "01"],
	["name" => "Huyện Gia Lâm", "code" => "018", "parent_code" => "01"],
	["name" => "Quận Nam Từ Liêm", "code" => "019", "parent_code" => "01"],
	["name" => "Huyện Thanh Trì", "code" => "020", "parent_code" => "01"],
	["name" => "Quận Bắc Từ Liêm", "code" => "021", "parent_code" => "01"],
	["name" => "Thành phố Hà Giang", "code" => "024", "parent_code" => "02"],
	["name" => "Huyện Đồng Văn", "code" => "026", "parent_code" => "02"],
	["name" => "Huyện Mèo Vạc", "code" => "027", "parent_code" => "02"],
	["name" => "Huyện Yên Minh", "code" => "028", "parent_code" => "02"],
	["name" => "Huyện Quản Bạ", "code" => "029", "parent_code" => "02"],
	["name" => "Huyện Vị Xuyên", "code" => "030", "parent_code" => "02"],
	["name" => "Huyện Bắc Mê", "code" => "031", "parent_code" => "02"],
	["name" => "Huyện Hoàng Su Phì", "code" => "032", "parent_code" => "02"],
	["name" => "Huyện Xín Mần", "code" => "033", "parent_code" => "02"],
	["name" => "Huyện Bắc Quang", "code" => "034", "parent_code" => "02"],
	["name" => "Huyện Quang Bình", "code" => "035", "parent_code" => "02"],
	["name" => "Thành phố Cao Bằng", "code" => "040", "parent_code" => "04"],
	["name" => "Huyện Bảo Lâm", "code" => "042", "parent_code" => "04"],
	["name" => "Huyện Bảo Lạc", "code" => "043", "parent_code" => "04"],
	["name" => "Huyện Hà Quảng", "code" => "045", "parent_code" => "04"],
	["name" => "Huyện Trùng Khánh", "code" => "047", "parent_code" => "04"],
	["name" => "Huyện Hạ Lang", "code" => "048", "parent_code" => "04"],
	["name" => "Huyện Quảng Hòa", "code" => "049", "parent_code" => "04"],
	["name" => "Huyện Hoà An", "code" => "051", "parent_code" => "04"],
	["name" => "Huyện Nguyên Bình", "code" => "052", "parent_code" => "04"],
	["name" => "Huyện Thạch An", "code" => "053", "parent_code" => "04"],
	["name" => "Thành Phố Bắc Kạn", "code" => "058", "parent_code" => "06"],
	["name" => "Huyện Pác Nặm", "code" => "060", "parent_code" => "06"],
	["name" => "Huyện Ba Bể", "code" => "061", "parent_code" => "06"],
	["name" => "Huyện Ngân Sơn", "code" => "062", "parent_code" => "06"],
	["name" => "Huyện Bạch Thông", "code" => "063", "parent_code" => "06"],
	["name" => "Huyện Chợ Đồn", "code" => "064", "parent_code" => "06"],
	["name" => "Huyện Chợ Mới", "code" => "065", "parent_code" => "06"],
	["name" => "Huyện Na Rì", "code" => "066", "parent_code" => "06"],
	["name" => "Thành phố Tuyên Quang", "code" => "070", "parent_code" => "08"],
	["name" => "Huyện Lâm Bình", "code" => "071", "parent_code" => "08"],
	["name" => "Huyện Na Hang", "code" => "072", "parent_code" => "08"],
	["name" => "Huyện Chiêm Hóa", "code" => "073", "parent_code" => "08"],
	["name" => "Huyện Hàm Yên", "code" => "074", "parent_code" => "08"],
	["name" => "Huyện Yên Sơn", "code" => "075", "parent_code" => "08"],
	["name" => "Huyện Sơn Dương", "code" => "076", "parent_code" => "08"],
	["name" => "Thành phố Lào Cai", "code" => "080", "parent_code" => "10"],
	["name" => "Huyện Bát Xát", "code" => "082", "parent_code" => "10"],
	["name" => "Huyện Mường Khương", "code" => "083", "parent_code" => "10"],
	["name" => "Huyện Si Ma Cai", "code" => "084", "parent_code" => "10"],
	["name" => "Huyện Bắc Hà", "code" => "085", "parent_code" => "10"],
	["name" => "Huyện Bảo Thắng", "code" => "086", "parent_code" => "10"],
	["name" => "Huyện Bảo Yên", "code" => "087", "parent_code" => "10"],
	["name" => "Thị xã Sa Pa", "code" => "088", "parent_code" => "10"],
	["name" => "Huyện Văn Bàn", "code" => "089", "parent_code" => "10"],
	["name" => "Thành phố Điện Biên Phủ", "code" => "094", "parent_code" => "11"],
	["name" => "Thị xã Mường Lay", "code" => "095", "parent_code" => "11"],
	["name" => "Huyện Mường Nhé", "code" => "096", "parent_code" => "11"],
	["name" => "Huyện Mường Chà", "code" => "097", "parent_code" => "11"],
	["name" => "Huyện Tủa Chùa", "code" => "098", "parent_code" => "11"],
	["name" => "Huyện Tuần Giáo", "code" => "099", "parent_code" => "11"],
	["name" => "Huyện Điện Biên", "code" => "100", "parent_code" => "11"],
	["name" => "Huyện Điện Biên Đông", "code" => "101", "parent_code" => "11"],
	["name" => "Huyện Mường Ảng", "code" => "102", "parent_code" => "11"],
	["name" => "Huyện Nậm Pồ", "code" => "103", "parent_code" => "11"],
	["name" => "Thành phố Lai Châu", "code" => "105", "parent_code" => "12"],
	["name" => "Huyện Tam Đường", "code" => "106", "parent_code" => "12"],
	["name" => "Huyện Mường Tè", "code" => "107", "parent_code" => "12"],
	["name" => "Huyện Sìn Hồ", "code" => "108", "parent_code" => "12"],
	["name" => "Huyện Phong Thổ", "code" => "109", "parent_code" => "12"],
	["name" => "Huyện Than Uyên", "code" => "110", "parent_code" => "12"],
	["name" => "Huyện Tân Uyên", "code" => "111", "parent_code" => "12"],
	["name" => "Huyện Nậm Nhùn", "code" => "112", "parent_code" => "12"],
	["name" => "Thành phố Sơn La", "code" => "116", "parent_code" => "14"],
	["name" => "Huyện Quỳnh Nhai", "code" => "118", "parent_code" => "14"],
	["name" => "Huyện Thuận Châu", "code" => "119", "parent_code" => "14"],
	["name" => "Huyện Mường La", "code" => "120", "parent_code" => "14"],
	["name" => "Huyện Bắc Yên", "code" => "121", "parent_code" => "14"],
	["name" => "Huyện Phù Yên", "code" => "122", "parent_code" => "14"],
	["name" => "Huyện Mộc Châu", "code" => "123", "parent_code" => "14"],
	["name" => "Huyện Yên Châu", "code" => "124", "parent_code" => "14"],
	["name" => "Huyện Mai Sơn", "code" => "125", "parent_code" => "14"],
	["name" => "Huyện Sông Mã", "code" => "126", "parent_code" => "14"],
	["name" => "Huyện Sốp Cộp", "code" => "127", "parent_code" => "14"],
	["name" => "Huyện Vân Hồ", "code" => "128", "parent_code" => "14"],
	["name" => "Thành phố Yên Bái", "code" => "132", "parent_code" => "15"],
	["name" => "Thị xã Nghĩa Lộ", "code" => "133", "parent_code" => "15"],
	["name" => "Huyện Lục Yên", "code" => "135", "parent_code" => "15"],
	["name" => "Huyện Văn Yên", "code" => "136", "parent_code" => "15"],
	["name" => "Huyện Mù Căng Chải", "code" => "137", "parent_code" => "15"],
	["name" => "Huyện Trấn Yên", "code" => "138", "parent_code" => "15"],
	["name" => "Huyện Trạm Tấu", "code" => "139", "parent_code" => "15"],
	["name" => "Huyện Văn Chấn", "code" => "140", "parent_code" => "15"],
	["name" => "Huyện Yên Bình", "code" => "141", "parent_code" => "15"],
	["name" => "Thành phố Hòa Bình", "code" => "148", "parent_code" => "17"],
	["name" => "Huyện Đà Bắc", "code" => "150", "parent_code" => "17"],
	["name" => "Huyện Lương Sơn", "code" => "152", "parent_code" => "17"],
	["name" => "Huyện Kim Bôi", "code" => "153", "parent_code" => "17"],
	["name" => "Huyện Cao Phong", "code" => "154", "parent_code" => "17"],
	["name" => "Huyện Tân Lạc", "code" => "155", "parent_code" => "17"],
	["name" => "Huyện Mai Châu", "code" => "156", "parent_code" => "17"],
	["name" => "Huyện Lạc Sơn", "code" => "157", "parent_code" => "17"],
	["name" => "Huyện Yên Thủy", "code" => "158", "parent_code" => "17"],
	["name" => "Huyện Lạc Thủy", "code" => "159", "parent_code" => "17"],
	["name" => "Thành phố Thái Nguyên", "code" => "164", "parent_code" => "19"],
	["name" => "Thành phố Sông Công", "code" => "165", "parent_code" => "19"],
	["name" => "Huyện Định Hóa", "code" => "167", "parent_code" => "19"],
	["name" => "Huyện Phú Lương", "code" => "168", "parent_code" => "19"],
	["name" => "Huyện Đồng Hỷ", "code" => "169", "parent_code" => "19"],
	["name" => "Huyện Võ Nhai", "code" => "170", "parent_code" => "19"],
	["name" => "Huyện Đại Từ", "code" => "171", "parent_code" => "19"],
	["name" => "Thành phố Phổ Yên", "code" => "172", "parent_code" => "19"],
	["name" => "Huyện Phú Bình", "code" => "173", "parent_code" => "19"],
	["name" => "Thành phố Lạng Sơn", "code" => "178", "parent_code" => "20"],
	["name" => "Huyện Tràng Định", "code" => "180", "parent_code" => "20"],
	["name" => "Huyện Bình Gia", "code" => "181", "parent_code" => "20"],
	["name" => "Huyện Văn Lãng", "code" => "182", "parent_code" => "20"],
	["name" => "Huyện Cao Lộc", "code" => "183", "parent_code" => "20"],
	["name" => "Huyện Văn Quan", "code" => "184", "parent_code" => "20"],
	["name" => "Huyện Bắc Sơn", "code" => "185", "parent_code" => "20"],
	["name" => "Huyện Hữu Lũng", "code" => "186", "parent_code" => "20"],
	["name" => "Huyện Chi Lăng", "code" => "187", "parent_code" => "20"],
	["name" => "Huyện Lộc Bình", "code" => "188", "parent_code" => "20"],
	["name" => "Huyện Đình Lập", "code" => "189", "parent_code" => "20"],
	["name" => "Thành phố Hạ Long", "code" => "193", "parent_code" => "22"],
	["name" => "Thành phố Móng Cái", "code" => "194", "parent_code" => "22"],
	["name" => "Thành phố Cẩm Phả", "code" => "195", "parent_code" => "22"],
	["name" => "Thành phố Uông Bí", "code" => "196", "parent_code" => "22"],
	["name" => "Huyện Bình Liêu", "code" => "198", "parent_code" => "22"],
	["name" => "Huyện Tiên Yên", "code" => "199", "parent_code" => "22"],
	["name" => "Huyện Đầm Hà", "code" => "200", "parent_code" => "22"],
	["name" => "Huyện Hải Hà", "code" => "201", "parent_code" => "22"],
	["name" => "Huyện Ba Chẽ", "code" => "202", "parent_code" => "22"],
	["name" => "Huyện Vân Đồn", "code" => "203", "parent_code" => "22"],
	["name" => "Thị xã Đông Triều", "code" => "205", "parent_code" => "22"],
	["name" => "Thị xã Quảng Yên", "code" => "206", "parent_code" => "22"],
	["name" => "Huyện Cô Tô", "code" => "207", "parent_code" => "22"],
	["name" => "Thành phố Bắc Giang", "code" => "213", "parent_code" => "24"],
	["name" => "Huyện Yên Thế", "code" => "215", "parent_code" => "24"],
	["name" => "Huyện Tân Yên", "code" => "216", "parent_code" => "24"],
	["name" => "Huyện Lạng Giang", "code" => "217", "parent_code" => "24"],
	["name" => "Huyện Lục Nam", "code" => "218", "parent_code" => "24"],
	["name" => "Huyện Lục Ngạn", "code" => "219", "parent_code" => "24"],
	["name" => "Huyện Sơn Động", "code" => "220", "parent_code" => "24"],
	["name" => "Huyện Yên Dũng", "code" => "221", "parent_code" => "24"],
	["name" => "Huyện Việt Yên", "code" => "222", "parent_code" => "24"],
	["name" => "Huyện Hiệp Hòa", "code" => "223", "parent_code" => "24"],
	["name" => "Thành phố Việt Trì", "code" => "227", "parent_code" => "25"],
	["name" => "Thị xã Phú Thọ", "code" => "228", "parent_code" => "25"],
	["name" => "Huyện Đoan Hùng", "code" => "230", "parent_code" => "25"],
	["name" => "Huyện Hạ Hoà", "code" => "231", "parent_code" => "25"],
	["name" => "Huyện Thanh Ba", "code" => "232", "parent_code" => "25"],
	["name" => "Huyện Phù Ninh", "code" => "233", "parent_code" => "25"],
	["name" => "Huyện Yên Lập", "code" => "234", "parent_code" => "25"],
	["name" => "Huyện Cẩm Khê", "code" => "235", "parent_code" => "25"],
	["name" => "Huyện Tam Nông", "code" => "236", "parent_code" => "25"],
	["name" => "Huyện Lâm Thao", "code" => "237", "parent_code" => "25"],
	["name" => "Huyện Thanh Sơn", "code" => "238", "parent_code" => "25"],
	["name" => "Huyện Thanh Thuỷ", "code" => "239", "parent_code" => "25"],
	["name" => "Huyện Tân Sơn", "code" => "240", "parent_code" => "25"],
	["name" => "Thành phố Vĩnh Yên", "code" => "243", "parent_code" => "26"],
	["name" => "Thành phố Phúc Yên", "code" => "244", "parent_code" => "26"],
	["name" => "Huyện Lập Thạch", "code" => "246", "parent_code" => "26"],
	["name" => "Huyện Tam Dương", "code" => "247", "parent_code" => "26"],
	["name" => "Huyện Tam Đảo", "code" => "248", "parent_code" => "26"],
	["name" => "Huyện Bình Xuyên", "code" => "249", "parent_code" => "26"],
	["name" => "Huyện Mê Linh", "code" => "250", "parent_code" => "01"],
	["name" => "Huyện Yên Lạc", "code" => "251", "parent_code" => "26"],
	["name" => "Huyện Vĩnh Tường", "code" => "252", "parent_code" => "26"],
	["name" => "Huyện Sông Lô", "code" => "253", "parent_code" => "26"],
	["name" => "Thành phố Bắc Ninh", "code" => "256", "parent_code" => "27"],
	["name" => "Huyện Yên Phong", "code" => "258", "parent_code" => "27"],
	["name" => "Thị xã Quế Võ", "code" => "259", "parent_code" => "27"],
	["name" => "Huyện Tiên Du", "code" => "260", "parent_code" => "27"],
	["name" => "Thành phố Từ Sơn", "code" => "261", "parent_code" => "27"],
	["name" => "Thị xã Thuận Thành", "code" => "262", "parent_code" => "27"],
	["name" => "Huyện Gia Bình", "code" => "263", "parent_code" => "27"],
	["name" => "Huyện Lương Tài", "code" => "264", "parent_code" => "27"],
	["name" => "Quận Hà Đông", "code" => "268", "parent_code" => "01"],
	["name" => "Thị xã Sơn Tây", "code" => "269", "parent_code" => "01"],
	["name" => "Huyện Ba Vì", "code" => "271", "parent_code" => "01"],
	["name" => "Huyện Phúc Thọ", "code" => "272", "parent_code" => "01"],
	["name" => "Huyện Đan Phượng", "code" => "273", "parent_code" => "01"],
	["name" => "Huyện Hoài Đức", "code" => "274", "parent_code" => "01"],
	["name" => "Huyện Quốc Oai", "code" => "275", "parent_code" => "01"],
	["name" => "Huyện Thạch Thất", "code" => "276", "parent_code" => "01"],
	["name" => "Huyện Chương Mỹ", "code" => "277", "parent_code" => "01"],
	["name" => "Huyện Thanh Oai", "code" => "278", "parent_code" => "01"],
	["name" => "Huyện Thường Tín", "code" => "279", "parent_code" => "01"],
	["name" => "Huyện Phú Xuyên", "code" => "280", "parent_code" => "01"],
	["name" => "Huyện Ứng Hòa", "code" => "281", "parent_code" => "01"],
	["name" => "Huyện Mỹ Đức", "code" => "282", "parent_code" => "01"],
	["name" => "Thành phố Hải Dương", "code" => "288", "parent_code" => "30"],
	["name" => "Thành phố Chí Linh", "code" => "290", "parent_code" => "30"],
	["name" => "Huyện Nam Sách", "code" => "291", "parent_code" => "30"],
	["name" => "Thị xã Kinh Môn", "code" => "292", "parent_code" => "30"],
	["name" => "Huyện Kim Thành", "code" => "293", "parent_code" => "30"],
	["name" => "Huyện Thanh Hà", "code" => "294", "parent_code" => "30"],
	["name" => "Huyện Cẩm Giàng", "code" => "295", "parent_code" => "30"],
	["name" => "Huyện Bình Giang", "code" => "296", "parent_code" => "30"],
	["name" => "Huyện Gia Lộc", "code" => "297", "parent_code" => "30"],
	["name" => "Huyện Tứ Kỳ", "code" => "298", "parent_code" => "30"],
	["name" => "Huyện Ninh Giang", "code" => "299", "parent_code" => "30"],
	["name" => "Huyện Thanh Miện", "code" => "300", "parent_code" => "30"],
	["name" => "Quận Hồng Bàng", "code" => "303", "parent_code" => "31"],
	["name" => "Quận Ngô Quyền", "code" => "304", "parent_code" => "31"],
	["name" => "Quận Lê Chân", "code" => "305", "parent_code" => "31"],
	["name" => "Quận Hải An", "code" => "306", "parent_code" => "31"],
	["name" => "Quận Kiến An", "code" => "307", "parent_code" => "31"],
	["name" => "Quận Đồ Sơn", "code" => "308", "parent_code" => "31"],
	["name" => "Quận Dương Kinh", "code" => "309", "parent_code" => "31"],
	["name" => "Huyện Thuỷ Nguyên", "code" => "311", "parent_code" => "31"],
	["name" => "Huyện An Dương", "code" => "312", "parent_code" => "31"],
	["name" => "Huyện An Lão", "code" => "313", "parent_code" => "31"],
	["name" => "Huyện Kiến Thuỵ", "code" => "314", "parent_code" => "31"],
	["name" => "Huyện Tiên Lãng", "code" => "315", "parent_code" => "31"],
	["name" => "Huyện Vĩnh Bảo", "code" => "316", "parent_code" => "31"],
	["name" => "Huyện Cát Hải", "code" => "317", "parent_code" => "31"],
	["name" => "Huyện Bạch Long Vĩ", "code" => "318", "parent_code" => "31"],
	["name" => "Thành phố Hưng Yên", "code" => "323", "parent_code" => "33"],
	["name" => "Huyện Văn Lâm", "code" => "325", "parent_code" => "33"],
	["name" => "Huyện Văn Giang", "code" => "326", "parent_code" => "33"],
	["name" => "Huyện Yên Mỹ", "code" => "327", "parent_code" => "33"],
	["name" => "Thị xã Mỹ Hào", "code" => "328", "parent_code" => "33"],
	["name" => "Huyện Ân Thi", "code" => "329", "parent_code" => "33"],
	["name" => "Huyện Khoái Châu", "code" => "330", "parent_code" => "33"],
	["name" => "Huyện Kim Động", "code" => "331", "parent_code" => "33"],
	["name" => "Huyện Tiên Lữ", "code" => "332", "parent_code" => "33"],
	["name" => "Huyện Phù Cừ", "code" => "333", "parent_code" => "33"],
	["name" => "Thành phố Thái Bình", "code" => "336", "parent_code" => "34"],
	["name" => "Huyện Quỳnh Phụ", "code" => "338", "parent_code" => "34"],
	["name" => "Huyện Hưng Hà", "code" => "339", "parent_code" => "34"],
	["name" => "Huyện Đông Hưng", "code" => "340", "parent_code" => "34"],
	["name" => "Huyện Thái Thụy", "code" => "341", "parent_code" => "34"],
	["name" => "Huyện Tiền Hải", "code" => "342", "parent_code" => "34"],
	["name" => "Huyện Kiến Xương", "code" => "343", "parent_code" => "34"],
	["name" => "Huyện Vũ Thư", "code" => "344", "parent_code" => "34"],
	["name" => "Thành phố Phủ Lý", "code" => "347", "parent_code" => "35"],
	["name" => "Thị xã Duy Tiên", "code" => "349", "parent_code" => "35"],
	["name" => "Huyện Kim Bảng", "code" => "350", "parent_code" => "35"],
	["name" => "Huyện Thanh Liêm", "code" => "351", "parent_code" => "35"],
	["name" => "Huyện Bình Lục", "code" => "352", "parent_code" => "35"],
	["name" => "Huyện Lý Nhân", "code" => "353", "parent_code" => "35"],
	["name" => "Thành phố Nam Định", "code" => "356", "parent_code" => "36"],
	["name" => "Huyện Mỹ Lộc", "code" => "358", "parent_code" => "36"],
	["name" => "Huyện Vụ Bản", "code" => "359", "parent_code" => "36"],
	["name" => "Huyện Ý Yên", "code" => "360", "parent_code" => "36"],
	["name" => "Huyện Nghĩa Hưng", "code" => "361", "parent_code" => "36"],
	["name" => "Huyện Nam Trực", "code" => "362", "parent_code" => "36"],
	["name" => "Huyện Trực Ninh", "code" => "363", "parent_code" => "36"],
	["name" => "Huyện Xuân Trường", "code" => "364", "parent_code" => "36"],
	["name" => "Huyện Giao Thủy", "code" => "365", "parent_code" => "36"],
	["name" => "Huyện Hải Hậu", "code" => "366", "parent_code" => "36"],
	["name" => "Thành phố Ninh Bình", "code" => "369", "parent_code" => "37"],
	["name" => "Thành phố Tam Điệp", "code" => "370", "parent_code" => "37"],
	["name" => "Huyện Nho Quan", "code" => "372", "parent_code" => "37"],
	["name" => "Huyện Gia Viễn", "code" => "373", "parent_code" => "37"],
	["name" => "Huyện Hoa Lư", "code" => "374", "parent_code" => "37"],
	["name" => "Huyện Yên Khánh", "code" => "375", "parent_code" => "37"],
	["name" => "Huyện Kim Sơn", "code" => "376", "parent_code" => "37"],
	["name" => "Huyện Yên Mô", "code" => "377", "parent_code" => "37"],
	["name" => "Thành phố Thanh Hóa", "code" => "380", "parent_code" => "38"],
	["name" => "Thị xã Bỉm Sơn", "code" => "381", "parent_code" => "38"],
	["name" => "Thành phố Sầm Sơn", "code" => "382", "parent_code" => "38"],
	["name" => "Huyện Mường Lát", "code" => "384", "parent_code" => "38"],
	["name" => "Huyện Quan Hóa", "code" => "385", "parent_code" => "38"],
	["name" => "Huyện Bá Thước", "code" => "386", "parent_code" => "38"],
	["name" => "Huyện Quan Sơn", "code" => "387", "parent_code" => "38"],
	["name" => "Huyện Lang Chánh", "code" => "388", "parent_code" => "38"],
	["name" => "Huyện Ngọc Lặc", "code" => "389", "parent_code" => "38"],
	["name" => "Huyện Cẩm Thủy", "code" => "390", "parent_code" => "38"],
	["name" => "Huyện Thạch Thành", "code" => "391", "parent_code" => "38"],
	["name" => "Huyện Hà Trung", "code" => "392", "parent_code" => "38"],
	["name" => "Huyện Vĩnh Lộc", "code" => "393", "parent_code" => "38"],
	["name" => "Huyện Yên Định", "code" => "394", "parent_code" => "38"],
	["name" => "Huyện Thọ Xuân", "code" => "395", "parent_code" => "38"],
	["name" => "Huyện Thường Xuân", "code" => "396", "parent_code" => "38"],
	["name" => "Huyện Triệu Sơn", "code" => "397", "parent_code" => "38"],
	["name" => "Huyện Thiệu Hóa", "code" => "398", "parent_code" => "38"],
	["name" => "Huyện Hoằng Hóa", "code" => "399", "parent_code" => "38"],
	["name" => "Huyện Hậu Lộc", "code" => "400", "parent_code" => "38"],
	["name" => "Huyện Nga Sơn", "code" => "401", "parent_code" => "38"],
	["name" => "Huyện Như Xuân", "code" => "402", "parent_code" => "38"],
	["name" => "Huyện Như Thanh", "code" => "403", "parent_code" => "38"],
	["name" => "Huyện Nông Cống", "code" => "404", "parent_code" => "38"],
	["name" => "Huyện Đông Sơn", "code" => "405", "parent_code" => "38"],
	["name" => "Huyện Quảng Xương", "code" => "406", "parent_code" => "38"],
	["name" => "Thị xã Nghi Sơn", "code" => "407", "parent_code" => "38"],
	["name" => "Thành phố Vinh", "code" => "412", "parent_code" => "40"],
	["name" => "Thị xã Cửa Lò", "code" => "413", "parent_code" => "40"],
	["name" => "Thị xã Thái Hoà", "code" => "414", "parent_code" => "40"],
	["name" => "Huyện Quế Phong", "code" => "415", "parent_code" => "40"],
	["name" => "Huyện Quỳ Châu", "code" => "416", "parent_code" => "40"],
	["name" => "Huyện Kỳ Sơn", "code" => "417", "parent_code" => "40"],
	["name" => "Huyện Tương Dương", "code" => "418", "parent_code" => "40"],
	["name" => "Huyện Nghĩa Đàn", "code" => "419", "parent_code" => "40"],
	["name" => "Huyện Quỳ Hợp", "code" => "420", "parent_code" => "40"],
	["name" => "Huyện Quỳnh Lưu", "code" => "421", "parent_code" => "40"],
	["name" => "Huyện Con Cuông", "code" => "422", "parent_code" => "40"],
	["name" => "Huyện Tân Kỳ", "code" => "423", "parent_code" => "40"],
	["name" => "Huyện Anh Sơn", "code" => "424", "parent_code" => "40"],
	["name" => "Huyện Diễn Châu", "code" => "425", "parent_code" => "40"],
	["name" => "Huyện Yên Thành", "code" => "426", "parent_code" => "40"],
	["name" => "Huyện Đô Lương", "code" => "427", "parent_code" => "40"],
	["name" => "Huyện Thanh Chương", "code" => "428", "parent_code" => "40"],
	["name" => "Huyện Nghi Lộc", "code" => "429", "parent_code" => "40"],
	["name" => "Huyện Nam Đàn", "code" => "430", "parent_code" => "40"],
	["name" => "Huyện Hưng Nguyên", "code" => "431", "parent_code" => "40"],
	["name" => "Thị xã Hoàng Mai", "code" => "432", "parent_code" => "40"],
	["name" => "Thành phố Hà Tĩnh", "code" => "436", "parent_code" => "42"],
	["name" => "Thị xã Hồng Lĩnh", "code" => "437", "parent_code" => "42"],
	["name" => "Huyện Hương Sơn", "code" => "439", "parent_code" => "42"],
	["name" => "Huyện Đức Thọ", "code" => "440", "parent_code" => "42"],
	["name" => "Huyện Vũ Quang", "code" => "441", "parent_code" => "42"],
	["name" => "Huyện Nghi Xuân", "code" => "442", "parent_code" => "42"],
	["name" => "Huyện Can Lộc", "code" => "443", "parent_code" => "42"],
	["name" => "Huyện Hương Khê", "code" => "444", "parent_code" => "42"],
	["name" => "Huyện Thạch Hà", "code" => "445", "parent_code" => "42"],
	["name" => "Huyện Cẩm Xuyên", "code" => "446", "parent_code" => "42"],
	["name" => "Huyện Kỳ Anh", "code" => "447", "parent_code" => "42"],
	["name" => "Huyện Lộc Hà", "code" => "448", "parent_code" => "42"],
	["name" => "Thị xã Kỳ Anh", "code" => "449", "parent_code" => "42"],
	["name" => "Thành Phố Đồng Hới", "code" => "450", "parent_code" => "44"],
	["name" => "Huyện Minh Hóa", "code" => "452", "parent_code" => "44"],
	["name" => "Huyện Tuyên Hóa", "code" => "453", "parent_code" => "44"],
	["name" => "Huyện Quảng Trạch", "code" => "454", "parent_code" => "44"],
	["name" => "Huyện Bố Trạch", "code" => "455", "parent_code" => "44"],
	["name" => "Huyện Quảng Ninh", "code" => "456", "parent_code" => "44"],
	["name" => "Huyện Lệ Thủy", "code" => "457", "parent_code" => "44"],
	["name" => "Thị xã Ba Đồn", "code" => "458", "parent_code" => "44"],
	["name" => "Thành phố Đông Hà", "code" => "461", "parent_code" => "45"],
	["name" => "Thị xã Quảng Trị", "code" => "462", "parent_code" => "45"],
	["name" => "Huyện Vĩnh Linh", "code" => "464", "parent_code" => "45"],
	["name" => "Huyện Hướng Hóa", "code" => "465", "parent_code" => "45"],
	["name" => "Huyện Gio Linh", "code" => "466", "parent_code" => "45"],
	["name" => "Huyện Đa Krông", "code" => "467", "parent_code" => "45"],
	["name" => "Huyện Cam Lộ", "code" => "468", "parent_code" => "45"],
	["name" => "Huyện Triệu Phong", "code" => "469", "parent_code" => "45"],
	["name" => "Huyện Hải Lăng", "code" => "470", "parent_code" => "45"],
	["name" => "Huyện Cồn Cỏ", "code" => "471", "parent_code" => "45"],
	["name" => "Thành phố Huế", "code" => "474", "parent_code" => "46"],
	["name" => "Huyện Phong Điền", "code" => "476", "parent_code" => "46"],
	["name" => "Huyện Quảng Điền", "code" => "477", "parent_code" => "46"],
	["name" => "Huyện Phú Vang", "code" => "478", "parent_code" => "46"],
	["name" => "Thị xã Hương Thủy", "code" => "479", "parent_code" => "46"],
	["name" => "Thị xã Hương Trà", "code" => "480", "parent_code" => "46"],
	["name" => "Huyện A Lưới", "code" => "481", "parent_code" => "46"],
	["name" => "Huyện Phú Lộc", "code" => "482", "parent_code" => "46"],
	["name" => "Huyện Nam Đông", "code" => "483", "parent_code" => "46"],
	["name" => "Quận Liên Chiểu", "code" => "490", "parent_code" => "48"],
	["name" => "Quận Thanh Khê", "code" => "491", "parent_code" => "48"],
	["name" => "Quận Hải Châu", "code" => "492", "parent_code" => "48"],
	["name" => "Quận Sơn Trà", "code" => "493", "parent_code" => "48"],
	["name" => "Quận Ngũ Hành Sơn", "code" => "494", "parent_code" => "48"],
	["name" => "Quận Cẩm Lệ", "code" => "495", "parent_code" => "48"],
	["name" => "Huyện Hòa Vang", "code" => "497", "parent_code" => "48"],
	["name" => "Huyện Hoàng Sa", "code" => "498", "parent_code" => "48"],
	["name" => "Thành phố Tam Kỳ", "code" => "502", "parent_code" => "49"],
	["name" => "Thành phố Hội An", "code" => "503", "parent_code" => "49"],
	["name" => "Huyện Tây Giang", "code" => "504", "parent_code" => "49"],
	["name" => "Huyện Đông Giang", "code" => "505", "parent_code" => "49"],
	["name" => "Huyện Đại Lộc", "code" => "506", "parent_code" => "49"],
	["name" => "Thị xã Điện Bàn", "code" => "507", "parent_code" => "49"],
	["name" => "Huyện Duy Xuyên", "code" => "508", "parent_code" => "49"],
	["name" => "Huyện Quế Sơn", "code" => "509", "parent_code" => "49"],
	["name" => "Huyện Nam Giang", "code" => "510", "parent_code" => "49"],
	["name" => "Huyện Phước Sơn", "code" => "511", "parent_code" => "49"],
	["name" => "Huyện Hiệp Đức", "code" => "512", "parent_code" => "49"],
	["name" => "Huyện Thăng Bình", "code" => "513", "parent_code" => "49"],
	["name" => "Huyện Tiên Phước", "code" => "514", "parent_code" => "49"],
	["name" => "Huyện Bắc Trà My", "code" => "515", "parent_code" => "49"],
	["name" => "Huyện Nam Trà My", "code" => "516", "parent_code" => "49"],
	["name" => "Huyện Núi Thành", "code" => "517", "parent_code" => "49"],
	["name" => "Huyện Phú Ninh", "code" => "518", "parent_code" => "49"],
	["name" => "Huyện Nông Sơn", "code" => "519", "parent_code" => "49"],
	["name" => "Thành phố Quảng Ngãi", "code" => "522", "parent_code" => "51"],
	["name" => "Huyện Bình Sơn", "code" => "524", "parent_code" => "51"],
	["name" => "Huyện Trà Bồng", "code" => "525", "parent_code" => "51"],
	["name" => "Huyện Sơn Tịnh", "code" => "527", "parent_code" => "51"],
	["name" => "Huyện Tư Nghĩa", "code" => "528", "parent_code" => "51"],
	["name" => "Huyện Sơn Hà", "code" => "529", "parent_code" => "51"],
	["name" => "Huyện Sơn Tây", "code" => "530", "parent_code" => "51"],
	["name" => "Huyện Minh Long", "code" => "531", "parent_code" => "51"],
	["name" => "Huyện Nghĩa Hành", "code" => "532", "parent_code" => "51"],
	["name" => "Huyện Mộ Đức", "code" => "533", "parent_code" => "51"],
	["name" => "Thị xã Đức Phổ", "code" => "534", "parent_code" => "51"],
	["name" => "Huyện Ba Tơ", "code" => "535", "parent_code" => "51"],
	["name" => "Huyện Lý Sơn", "code" => "536", "parent_code" => "51"],
	["name" => "Thành phố Quy Nhơn", "code" => "540", "parent_code" => "52"],
	["name" => "Huyện An Lão", "code" => "542", "parent_code" => "52"],
	["name" => "Thị xã Hoài Nhơn", "code" => "543", "parent_code" => "52"],
	["name" => "Huyện Hoài Ân", "code" => "544", "parent_code" => "52"],
	["name" => "Huyện Phù Mỹ", "code" => "545", "parent_code" => "52"],
	["name" => "Huyện Vĩnh Thạnh", "code" => "546", "parent_code" => "52"],
	["name" => "Huyện Tây Sơn", "code" => "547", "parent_code" => "52"],
	["name" => "Huyện Phù Cát", "code" => "548", "parent_code" => "52"],
	["name" => "Thị xã An Nhơn", "code" => "549", "parent_code" => "52"],
	["name" => "Huyện Tuy Phước", "code" => "550", "parent_code" => "52"],
	["name" => "Huyện Vân Canh", "code" => "551", "parent_code" => "52"],
	["name" => "Thành phố Tuy Hoà", "code" => "555", "parent_code" => "54"],
	["name" => "Thị xã Sông Cầu", "code" => "557", "parent_code" => "54"],
	["name" => "Huyện Đồng Xuân", "code" => "558", "parent_code" => "54"],
	["name" => "Huyện Tuy An", "code" => "559", "parent_code" => "54"],
	["name" => "Huyện Sơn Hòa", "code" => "560", "parent_code" => "54"],
	["name" => "Huyện Sông Hinh", "code" => "561", "parent_code" => "54"],
	["name" => "Huyện Tây Hoà", "code" => "562", "parent_code" => "54"],
	["name" => "Huyện Phú Hoà", "code" => "563", "parent_code" => "54"],
	["name" => "Thị xã Đông Hòa", "code" => "564", "parent_code" => "54"],
	["name" => "Thành phố Nha Trang", "code" => "568", "parent_code" => "56"],
	["name" => "Thành phố Cam Ranh", "code" => "569", "parent_code" => "56"],
	["name" => "Huyện Cam Lâm", "code" => "570", "parent_code" => "56"],
	["name" => "Huyện Vạn Ninh", "code" => "571", "parent_code" => "56"],
	["name" => "Thị xã Ninh Hòa", "code" => "572", "parent_code" => "56"],
	["name" => "Huyện Khánh Vĩnh", "code" => "573", "parent_code" => "56"],
	["name" => "Huyện Diên Khánh", "code" => "574", "parent_code" => "56"],
	["name" => "Huyện Khánh Sơn", "code" => "575", "parent_code" => "56"],
	["name" => "Huyện Trường Sa", "code" => "576", "parent_code" => "56"],
	["name" => "Thành phố Phan Rang-Tháp Chàm", "code" => "582", "parent_code" => "58"],
	["name" => "Huyện Bác Ái", "code" => "584", "parent_code" => "58"],
	["name" => "Huyện Ninh Sơn", "code" => "585", "parent_code" => "58"],
	["name" => "Huyện Ninh Hải", "code" => "586", "parent_code" => "58"],
	["name" => "Huyện Ninh Phước", "code" => "587", "parent_code" => "58"],
	["name" => "Huyện Thuận Bắc", "code" => "588", "parent_code" => "58"],
	["name" => "Huyện Thuận Nam", "code" => "589", "parent_code" => "58"],
	["name" => "Thành phố Phan Thiết", "code" => "593", "parent_code" => "60"],
	["name" => "Thị xã La Gi", "code" => "594", "parent_code" => "60"],
	["name" => "Huyện Tuy Phong", "code" => "595", "parent_code" => "60"],
	["name" => "Huyện Bắc Bình", "code" => "596", "parent_code" => "60"],
	["name" => "Huyện Hàm Thuận Bắc", "code" => "597", "parent_code" => "60"],
	["name" => "Huyện Hàm Thuận Nam", "code" => "598", "parent_code" => "60"],
	["name" => "Huyện Tánh Linh", "code" => "599", "parent_code" => "60"],
	["name" => "Huyện Đức Linh", "code" => "600", "parent_code" => "60"],
	["name" => "Huyện Hàm Tân", "code" => "601", "parent_code" => "60"],
	["name" => "Huyện Phú Quí", "code" => "602", "parent_code" => "60"],
	["name" => "Thành phố Kon Tum", "code" => "608", "parent_code" => "62"],
	["name" => "Huyện Đắk Glei", "code" => "610", "parent_code" => "62"],
	["name" => "Huyện Ngọc Hồi", "code" => "611", "parent_code" => "62"],
	["name" => "Huyện Đắk Tô", "code" => "612", "parent_code" => "62"],
	["name" => "Huyện Kon Plông", "code" => "613", "parent_code" => "62"],
	["name" => "Huyện Kon Rẫy", "code" => "614", "parent_code" => "62"],
	["name" => "Huyện Đắk Hà", "code" => "615", "parent_code" => "62"],
	["name" => "Huyện Sa Thầy", "code" => "616", "parent_code" => "62"],
	["name" => "Huyện Tu Mơ Rông", "code" => "617", "parent_code" => "62"],
	["name" => "Huyện Ia H' Drai", "code" => "618", "parent_code" => "62"],
	["name" => "Thành phố Pleiku", "code" => "622", "parent_code" => "64"],
	["name" => "Thị xã An Khê", "code" => "623", "parent_code" => "64"],
	["name" => "Thị xã Ayun Pa", "code" => "624", "parent_code" => "64"],
	["name" => "Huyện KBang", "code" => "625", "parent_code" => "64"],
	["name" => "Huyện Đăk Đoa", "code" => "626", "parent_code" => "64"],
	["name" => "Huyện Chư Păh", "code" => "627", "parent_code" => "64"],
	["name" => "Huyện Ia Grai", "code" => "628", "parent_code" => "64"],
	["name" => "Huyện Mang Yang", "code" => "629", "parent_code" => "64"],
	["name" => "Huyện Kông Chro", "code" => "630", "parent_code" => "64"],
	["name" => "Huyện Đức Cơ", "code" => "631", "parent_code" => "64"],
	["name" => "Huyện Chư Prông", "code" => "632", "parent_code" => "64"],
	["name" => "Huyện Chư Sê", "code" => "633", "parent_code" => "64"],
	["name" => "Huyện Đăk Pơ", "code" => "634", "parent_code" => "64"],
	["name" => "Huyện Ia Pa", "code" => "635", "parent_code" => "64"],
	["name" => "Huyện Krông Pa", "code" => "637", "parent_code" => "64"],
	["name" => "Huyện Phú Thiện", "code" => "638", "parent_code" => "64"],
	["name" => "Huyện Chư Pưh", "code" => "639", "parent_code" => "64"],
	["name" => "Thành phố Buôn Ma Thuột", "code" => "643", "parent_code" => "66"],
	["name" => "Thị xã Buôn Hồ", "code" => "644", "parent_code" => "66"],
	["name" => "Huyện Ea H'leo", "code" => "645", "parent_code" => "66"],
	["name" => "Huyện Ea Súp", "code" => "646", "parent_code" => "66"],
	["name" => "Huyện Buôn Đôn", "code" => "647", "parent_code" => "66"],
	["name" => "Huyện Cư M'gar", "code" => "648", "parent_code" => "66"],
	["name" => "Huyện Krông Búk", "code" => "649", "parent_code" => "66"],
	["name" => "Huyện Krông Năng", "code" => "650", "parent_code" => "66"],
	["name" => "Huyện Ea Kar", "code" => "651", "parent_code" => "66"],
	["name" => "Huyện M'Đrắk", "code" => "652", "parent_code" => "66"],
	["name" => "Huyện Krông Bông", "code" => "653", "parent_code" => "66"],
	["name" => "Huyện Krông Pắc", "code" => "654", "parent_code" => "66"],
	["name" => "Huyện Krông A Na", "code" => "655", "parent_code" => "66"],
	["name" => "Huyện Lắk", "code" => "656", "parent_code" => "66"],
	["name" => "Huyện Cư Kuin", "code" => "657", "parent_code" => "66"],
	["name" => "Thành phố Gia Nghĩa", "code" => "660", "parent_code" => "67"],
	["name" => "Huyện Đăk Glong", "code" => "661", "parent_code" => "67"],
	["name" => "Huyện Cư Jút", "code" => "662", "parent_code" => "67"],
	["name" => "Huyện Đắk Mil", "code" => "663", "parent_code" => "67"],
	["name" => "Huyện Krông Nô", "code" => "664", "parent_code" => "67"],
	["name" => "Huyện Đắk Song", "code" => "665", "parent_code" => "67"],
	["name" => "Huyện Đắk R'Lấp", "code" => "666", "parent_code" => "67"],
	["name" => "Huyện Tuy Đức", "code" => "667", "parent_code" => "67"],
	["name" => "Thành phố Đà Lạt", "code" => "672", "parent_code" => "68"],
	["name" => "Thành phố Bảo Lộc", "code" => "673", "parent_code" => "68"],
	["name" => "Huyện Đam Rông", "code" => "674", "parent_code" => "68"],
	["name" => "Huyện Lạc Dương", "code" => "675", "parent_code" => "68"],
	["name" => "Huyện Lâm Hà", "code" => "676", "parent_code" => "68"],
	["name" => "Huyện Đơn Dương", "code" => "677", "parent_code" => "68"],
	["name" => "Huyện Đức Trọng", "code" => "678", "parent_code" => "68"],
	["name" => "Huyện Di Linh", "code" => "679", "parent_code" => "68"],
	["name" => "Huyện Bảo Lâm", "code" => "680", "parent_code" => "68"],
	["name" => "Huyện Đạ Huoai", "code" => "681", "parent_code" => "68"],
	["name" => "Huyện Đạ Tẻh", "code" => "682", "parent_code" => "68"],
	["name" => "Huyện Cát Tiên", "code" => "683", "parent_code" => "68"],
	["name" => "Thị xã Phước Long", "code" => "688", "parent_code" => "70"],
	["name" => "Thành phố Đồng Xoài", "code" => "689", "parent_code" => "70"],
	["name" => "Thị xã Bình Long", "code" => "690", "parent_code" => "70"],
	["name" => "Huyện Bù Gia Mập", "code" => "691", "parent_code" => "70"],
	["name" => "Huyện Lộc Ninh", "code" => "692", "parent_code" => "70"],
	["name" => "Huyện Bù Đốp", "code" => "693", "parent_code" => "70"],
	["name" => "Huyện Hớn Quản", "code" => "694", "parent_code" => "70"],
	["name" => "Huyện Đồng Phú", "code" => "695", "parent_code" => "70"],
	["name" => "Huyện Bù Đăng", "code" => "696", "parent_code" => "70"],
	["name" => "Thị xã Chơn Thành", "code" => "697", "parent_code" => "70"],
	["name" => "Huyện Phú Riềng", "code" => "698", "parent_code" => "70"],
	["name" => "Thành phố Tây Ninh", "code" => "703", "parent_code" => "72"],
	["name" => "Huyện Tân Biên", "code" => "705", "parent_code" => "72"],
	["name" => "Huyện Tân Châu", "code" => "706", "parent_code" => "72"],
	["name" => "Huyện Dương Minh Châu", "code" => "707", "parent_code" => "72"],
	["name" => "Huyện Châu Thành", "code" => "708", "parent_code" => "72"],
	["name" => "Thị xã Hòa Thành", "code" => "709", "parent_code" => "72"],
	["name" => "Huyện Gò Dầu", "code" => "710", "parent_code" => "72"],
	["name" => "Huyện Bến Cầu", "code" => "711", "parent_code" => "72"],
	["name" => "Thị xã Trảng Bàng", "code" => "712", "parent_code" => "72"],
	["name" => "Thành phố Thủ Dầu Một", "code" => "718", "parent_code" => "74"],
	["name" => "Huyện Bàu Bàng", "code" => "719", "parent_code" => "74"],
	["name" => "Huyện Dầu Tiếng", "code" => "720", "parent_code" => "74"],
	["name" => "Thị xã Bến Cát", "code" => "721", "parent_code" => "74"],
	["name" => "Huyện Phú Giáo", "code" => "722", "parent_code" => "74"],
	["name" => "Thành phố Tân Uyên", "code" => "723", "parent_code" => "74"],
	["name" => "Thành phố Dĩ An", "code" => "724", "parent_code" => "74"],
	["name" => "Thành phố Thuận An", "code" => "725", "parent_code" => "74"],
	["name" => "Huyện Bắc Tân Uyên", "code" => "726", "parent_code" => "74"],
	["name" => "Thành phố Biên Hòa", "code" => "731", "parent_code" => "75"],
	["name" => "Thành phố Long Khánh", "code" => "732", "parent_code" => "75"],
	["name" => "Huyện Tân Phú", "code" => "734", "parent_code" => "75"],
	["name" => "Huyện Vĩnh Cửu", "code" => "735", "parent_code" => "75"],
	["name" => "Huyện Định Quán", "code" => "736", "parent_code" => "75"],
	["name" => "Huyện Trảng Bom", "code" => "737", "parent_code" => "75"],
	["name" => "Huyện Thống Nhất", "code" => "738", "parent_code" => "75"],
	["name" => "Huyện Cẩm Mỹ", "code" => "739", "parent_code" => "75"],
	["name" => "Huyện Long Thành", "code" => "740", "parent_code" => "75"],
	["name" => "Huyện Xuân Lộc", "code" => "741", "parent_code" => "75"],
	["name" => "Huyện Nhơn Trạch", "code" => "742", "parent_code" => "75"],
	["name" => "Thành phố Vũng Tàu", "code" => "747", "parent_code" => "77"],
	["name" => "Thành phố Bà Rịa", "code" => "748", "parent_code" => "77"],
	["name" => "Huyện Châu Đức", "code" => "750", "parent_code" => "77"],
	["name" => "Huyện Xuyên Mộc", "code" => "751", "parent_code" => "77"],
	["name" => "Huyện Long Điền", "code" => "752", "parent_code" => "77"],
	["name" => "Huyện Đất Đỏ", "code" => "753", "parent_code" => "77"],
	["name" => "Thị xã Phú Mỹ", "code" => "754", "parent_code" => "77"],
	["name" => "Huyện Côn Đảo", "code" => "755", "parent_code" => "77"],
	["name" => "Quận 1", "code" => "760", "parent_code" => "79"],
	["name" => "Quận 12", "code" => "761", "parent_code" => "79"],
	["name" => "Quận Gò Vấp", "code" => "764", "parent_code" => "79"],
	["name" => "Quận Bình Thạnh", "code" => "765", "parent_code" => "79"],
	["name" => "Quận Tân Bình", "code" => "766", "parent_code" => "79"],
	["name" => "Quận Tân Phú", "code" => "767", "parent_code" => "79"],
	["name" => "Quận Phú Nhuận", "code" => "768", "parent_code" => "79"],
	["name" => "Thành phố Thủ Đức", "code" => "769", "parent_code" => "79"],
	["name" => "Quận 3", "code" => "770", "parent_code" => "79"],
	["name" => "Quận 10", "code" => "771", "parent_code" => "79"],
	["name" => "Quận 11", "code" => "772", "parent_code" => "79"],
	["name" => "Quận 4", "code" => "773", "parent_code" => "79"],
	["name" => "Quận 5", "code" => "774", "parent_code" => "79"],
	["name" => "Quận 6", "code" => "775", "parent_code" => "79"],
	["name" => "Quận 8", "code" => "776", "parent_code" => "79"],
	["name" => "Quận Bình Tân", "code" => "777", "parent_code" => "79"],
	["name" => "Quận 7", "code" => "778", "parent_code" => "79"],
	["name" => "Huyện Củ Chi", "code" => "783", "parent_code" => "79"],
	["name" => "Huyện Hóc Môn", "code" => "784", "parent_code" => "79"],
	["name" => "Huyện Bình Chánh", "code" => "785", "parent_code" => "79"],
	["name" => "Huyện Nhà Bè", "code" => "786", "parent_code" => "79"],
	["name" => "Huyện Cần Giờ", "code" => "787", "parent_code" => "79"],
	["name" => "Thành phố Tân An", "code" => "794", "parent_code" => "80"],
	["name" => "Thị xã Kiến Tường", "code" => "795", "parent_code" => "80"],
	["name" => "Huyện Tân Hưng", "code" => "796", "parent_code" => "80"],
	["name" => "Huyện Vĩnh Hưng", "code" => "797", "parent_code" => "80"],
	["name" => "Huyện Mộc Hóa", "code" => "798", "parent_code" => "80"],
	["name" => "Huyện Tân Thạnh", "code" => "799", "parent_code" => "80"],
	["name" => "Huyện Thạnh Hóa", "code" => "800", "parent_code" => "80"],
	["name" => "Huyện Đức Huệ", "code" => "801", "parent_code" => "80"],
	["name" => "Huyện Đức Hòa", "code" => "802", "parent_code" => "80"],
	["name" => "Huyện Bến Lức", "code" => "803", "parent_code" => "80"],
	["name" => "Huyện Thủ Thừa", "code" => "804", "parent_code" => "80"],
	["name" => "Huyện Tân Trụ", "code" => "805", "parent_code" => "80"],
	["name" => "Huyện Cần Đước", "code" => "806", "parent_code" => "80"],
	["name" => "Huyện Cần Giuộc", "code" => "807", "parent_code" => "80"],
	["name" => "Huyện Châu Thành", "code" => "808", "parent_code" => "80"],
	["name" => "Thành phố Mỹ Tho", "code" => "815", "parent_code" => "82"],
	["name" => "Thị xã Gò Công", "code" => "816", "parent_code" => "82"],
	["name" => "Thị xã Cai Lậy", "code" => "817", "parent_code" => "82"],
	["name" => "Huyện Tân Phước", "code" => "818", "parent_code" => "82"],
	["name" => "Huyện Cái Bè", "code" => "819", "parent_code" => "82"],
	["name" => "Huyện Cai Lậy", "code" => "820", "parent_code" => "82"],
	["name" => "Huyện Châu Thành", "code" => "821", "parent_code" => "82"],
	["name" => "Huyện Chợ Gạo", "code" => "822", "parent_code" => "82"],
	["name" => "Huyện Gò Công Tây", "code" => "823", "parent_code" => "82"],
	["name" => "Huyện Gò Công Đông", "code" => "824", "parent_code" => "82"],
	["name" => "Huyện Tân Phú Đông", "code" => "825", "parent_code" => "82"],
	["name" => "Thành phố Bến Tre", "code" => "829", "parent_code" => "83"],
	["name" => "Huyện Châu Thành", "code" => "831", "parent_code" => "83"],
	["name" => "Huyện Chợ Lách", "code" => "832", "parent_code" => "83"],
	["name" => "Huyện Mỏ Cày Nam", "code" => "833", "parent_code" => "83"],
	["name" => "Huyện Giồng Trôm", "code" => "834", "parent_code" => "83"],
	["name" => "Huyện Bình Đại", "code" => "835", "parent_code" => "83"],
	["name" => "Huyện Ba Tri", "code" => "836", "parent_code" => "83"],
	["name" => "Huyện Thạnh Phú", "code" => "837", "parent_code" => "83"],
	["name" => "Huyện Mỏ Cày Bắc", "code" => "838", "parent_code" => "83"],
	["name" => "Thành phố Trà Vinh", "code" => "842", "parent_code" => "84"],
	["name" => "Huyện Càng Long", "code" => "844", "parent_code" => "84"],
	["name" => "Huyện Cầu Kè", "code" => "845", "parent_code" => "84"],
	["name" => "Huyện Tiểu Cần", "code" => "846", "parent_code" => "84"],
	["name" => "Huyện Châu Thành", "code" => "847", "parent_code" => "84"],
	["name" => "Huyện Cầu Ngang", "code" => "848", "parent_code" => "84"],
	["name" => "Huyện Trà Cú", "code" => "849", "parent_code" => "84"],
	["name" => "Huyện Duyên Hải", "code" => "850", "parent_code" => "84"],
	["name" => "Thị xã Duyên Hải", "code" => "851", "parent_code" => "84"],
	["name" => "Thành phố Vĩnh Long", "code" => "855", "parent_code" => "86"],
	["name" => "Huyện Long Hồ", "code" => "857", "parent_code" => "86"],
	["name" => "Huyện Mang Thít", "code" => "858", "parent_code" => "86"],
	["name" => "Huyện  Vũng Liêm", "code" => "859", "parent_code" => "86"],
	["name" => "Huyện Tam Bình", "code" => "860", "parent_code" => "86"],
	["name" => "Thị xã Bình Minh", "code" => "861", "parent_code" => "86"],
	["name" => "Huyện Trà Ôn", "code" => "862", "parent_code" => "86"],
	["name" => "Huyện Bình Tân", "code" => "863", "parent_code" => "86"],
	["name" => "Thành phố Cao Lãnh", "code" => "866", "parent_code" => "87"],
	["name" => "Thành phố Sa Đéc", "code" => "867", "parent_code" => "87"],
	["name" => "Thành phố Hồng Ngự", "code" => "868", "parent_code" => "87"],
	["name" => "Huyện Tân Hồng", "code" => "869", "parent_code" => "87"],
	["name" => "Huyện Hồng Ngự", "code" => "870", "parent_code" => "87"],
	["name" => "Huyện Tam Nông", "code" => "871", "parent_code" => "87"],
	["name" => "Huyện Tháp Mười", "code" => "872", "parent_code" => "87"],
	["name" => "Huyện Cao Lãnh", "code" => "873", "parent_code" => "87"],
	["name" => "Huyện Thanh Bình", "code" => "874", "parent_code" => "87"],
	["name" => "Huyện Lấp Vò", "code" => "875", "parent_code" => "87"],
	["name" => "Huyện Lai Vung", "code" => "876", "parent_code" => "87"],
	["name" => "Huyện Châu Thành", "code" => "877", "parent_code" => "87"],
	["name" => "Thành phố Long Xuyên", "code" => "883", "parent_code" => "89"],
	["name" => "Thành phố Châu Đốc", "code" => "884", "parent_code" => "89"],
	["name" => "Huyện An Phú", "code" => "886", "parent_code" => "89"],
	["name" => "Thị xã Tân Châu", "code" => "887", "parent_code" => "89"],
	["name" => "Huyện Phú Tân", "code" => "888", "parent_code" => "89"],
	["name" => "Huyện Châu Phú", "code" => "889", "parent_code" => "89"],
	["name" => "Thị xã Tịnh Biên", "code" => "890", "parent_code" => "89"],
	["name" => "Huyện Tri Tôn", "code" => "891", "parent_code" => "89"],
	["name" => "Huyện Châu Thành", "code" => "892", "parent_code" => "89"],
	["name" => "Huyện Chợ Mới", "code" => "893", "parent_code" => "89"],
	["name" => "Huyện Thoại Sơn", "code" => "894", "parent_code" => "89"],
	["name" => "Thành phố Rạch Giá", "code" => "899", "parent_code" => "91"],
	["name" => "Thành phố Hà Tiên", "code" => "900", "parent_code" => "91"],
	["name" => "Huyện Kiên Lương", "code" => "902", "parent_code" => "91"],
	["name" => "Huyện Hòn Đất", "code" => "903", "parent_code" => "91"],
	["name" => "Huyện Tân Hiệp", "code" => "904", "parent_code" => "91"],
	["name" => "Huyện Châu Thành", "code" => "905", "parent_code" => "91"],
	["name" => "Huyện Giồng Riềng", "code" => "906", "parent_code" => "91"],
	["name" => "Huyện Gò Quao", "code" => "907", "parent_code" => "91"],
	["name" => "Huyện An Biên", "code" => "908", "parent_code" => "91"],
	["name" => "Huyện An Minh", "code" => "909", "parent_code" => "91"],
	["name" => "Huyện Vĩnh Thuận", "code" => "910", "parent_code" => "91"],
	["name" => "Thành phố Phú Quốc", "code" => "911", "parent_code" => "91"],
	["name" => "Huyện Kiên Hải", "code" => "912", "parent_code" => "91"],
	["name" => "Huyện U Minh Thượng", "code" => "913", "parent_code" => "91"],
	["name" => "Huyện Giang Thành", "code" => "914", "parent_code" => "91"],
	["name" => "Quận Ninh Kiều", "code" => "916", "parent_code" => "92"],
	["name" => "Quận Ô Môn", "code" => "917", "parent_code" => "92"],
	["name" => "Quận Bình Thuỷ", "code" => "918", "parent_code" => "92"],
	["name" => "Quận Cái Răng", "code" => "919", "parent_code" => "92"],
	["name" => "Quận Thốt Nốt", "code" => "923", "parent_code" => "92"],
	["name" => "Huyện Vĩnh Thạnh", "code" => "924", "parent_code" => "92"],
	["name" => "Huyện Cờ Đỏ", "code" => "925", "parent_code" => "92"],
	["name" => "Huyện Phong Điền", "code" => "926", "parent_code" => "92"],
	["name" => "Huyện Thới Lai", "code" => "927", "parent_code" => "92"],
	["name" => "Thành phố Vị Thanh", "code" => "930", "parent_code" => "93"],
	["name" => "Thành phố Ngã Bảy", "code" => "931", "parent_code" => "93"],
	["name" => "Huyện Châu Thành A", "code" => "932", "parent_code" => "93"],
	["name" => "Huyện Châu Thành", "code" => "933", "parent_code" => "93"],
	["name" => "Huyện Phụng Hiệp", "code" => "934", "parent_code" => "93"],
	["name" => "Huyện Vị Thuỷ", "code" => "935", "parent_code" => "93"],
	["name" => "Huyện Long Mỹ", "code" => "936", "parent_code" => "93"],
	["name" => "Thị xã Long Mỹ", "code" => "937", "parent_code" => "93"],
	["name" => "Thành phố Sóc Trăng", "code" => "941", "parent_code" => "94"],
	["name" => "Huyện Châu Thành", "code" => "942", "parent_code" => "94"],
	["name" => "Huyện Kế Sách", "code" => "943", "parent_code" => "94"],
	["name" => "Huyện Mỹ Tú", "code" => "944", "parent_code" => "94"],
	["name" => "Huyện Cù Lao Dung", "code" => "945", "parent_code" => "94"],
	["name" => "Huyện Long Phú", "code" => "946", "parent_code" => "94"],
	["name" => "Huyện Mỹ Xuyên", "code" => "947", "parent_code" => "94"],
	["name" => "Thị xã Ngã Năm", "code" => "948", "parent_code" => "94"],
	["name" => "Huyện Thạnh Trị", "code" => "949", "parent_code" => "94"],
	["name" => "Thị xã Vĩnh Châu", "code" => "950", "parent_code" => "94"],
	["name" => "Huyện Trần Đề", "code" => "951", "parent_code" => "94"],
	["name" => "Thành phố Bạc Liêu", "code" => "954", "parent_code" => "95"],
	["name" => "Huyện Hồng Dân", "code" => "956", "parent_code" => "95"],
	["name" => "Huyện Phước Long", "code" => "957", "parent_code" => "95"],
	["name" => "Huyện Vĩnh Lợi", "code" => "958", "parent_code" => "95"],
	["name" => "Thị xã Giá Rai", "code" => "959", "parent_code" => "95"],
	["name" => "Huyện Đông Hải", "code" => "960", "parent_code" => "95"],
	["name" => "Huyện Hoà Bình", "code" => "961", "parent_code" => "95"],
	["name" => "Thành phố Cà Mau", "code" => "964", "parent_code" => "96"],
	["name" => "Huyện U Minh", "code" => "966", "parent_code" => "96"],
	["name" => "Huyện Thới Bình", "code" => "967", "parent_code" => "96"],
	["name" => "Huyện Trần Văn Thời", "code" => "968", "parent_code" => "96"],
	["name" => "Huyện Cái Nước", "code" => "969", "parent_code" => "96"],
	["name" => "Huyện Đầm Dơi", "code" => "970", "parent_code" => "96"],
	["name" => "Huyện Năm Căn", "code" => "971", "parent_code" => "96"],
	["name" => "Huyện Phú Tân", "code" => "972", "parent_code" => "96"],
	["name" => "Huyện Ngọc Hiển", "code" => "973", "parent_code" => "96"],
];
