<?php
/**
 * N Framework
 *
 * WARNING: This file is part of the core N Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @since      0.0.1
 * @package    N
 * @subpackage N/config
 */

if (!defined('ABSPATH')):
	exit; // Exit if accessed directly.
endif;

return [
	'_sim_than_tai'      => 'Sim Thần Tài',
	'_sim_tho_dia'       => 'Sim Thổ Địa',
	'_sim_loc_phat'      => 'Sim lộc phát',
	'_sim_phat_loc'      => 'Sim phát lộc',
	'_sim_luc_quy'       => 'Sim lục quý',
	'_sim_ngu_quy'       => 'Sim ngũ quý',
	'_sim_tu_quy'        => 'Sim tứ quý',
	'_sim_tam_hoa_kep'   => 'Sim tam hoa kép',
	'_sim_tam_hoa_cuoi'  => 'Sim tam hoa cuối',
	'_sim_tam_hoa'       => 'Sim tam hoa',
	'_sim_tien_len'      => 'Sim tiến lên',
	'_sim_sanh_tien_len' => 'Sim sảnh tiến lên',
	'_sim_lap_kep'       => 'Sim lặp kép',
	'_sim_taxi'          => 'Sim taxi',
	'_sim_nam_sinh'      => 'Sim năm sinh',
	'_sim99k'            => 'Sim 99k',
];
