<?php
/**
 * N Framework
 *
 * WARNING: This file is part of the core N Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @since      0.0.1
 * @package    N
 * @subpackage N/lib/admin
 */

if (!defined('ABSPATH')):
	exit; // Exit if accessed directly.
endif;

/**
 * Add admin menus
 *
 * @since 0.0.1
 */
function _n_admin_menus(){
	add_submenu_page('edit.php?post_type=product', 'Nhập sim', 'Nhập sim', 'manage_options', 'sim-importer', '_n_sim_importer');
	add_submenu_page('edit.php?post_type=product', 'Nhập sim từ API', 'Nhập sim từ API', 'manage_options', 'sim-api-importer', '_n_sim_api_importer');
	add_submenu_page('edit.php?post_type=product', 'Nhập sim siêu data', 'Nhập sim siêu data', 'manage_options', 'sim-super-data-importer', '_n_sim_super_data_importer');
	add_submenu_page('edit.php?post_type=product', 'Nhập sim đã bán', 'Nhập sim đã bán', 'manage_options', 'sim-sold-out-importer', '_n_sim_sold_out_importer');
	add_submenu_page('edit.php?post_type=product', 'Nhập gói cước', 'Nhập gói cước', 'manage_options', 'sim-package-importer', '_n_package_importer');
	add_submenu_page('edit.php?post_type=product', 'Lịch sử nhập', 'Lịch sử nhập', 'manage_options', 'import-history', '_n_import_history');
	add_submenu_page('edit.php?post_type=product', 'Báo cáo', 'Báo cáo', 'manage_options', 'sim-report', '_n_sim_reports');
	add_submenu_page('edit.php?post_type=product', 'Báo cáo sim siêu data', 'Báo cáo sim siêu data', 'manage_options', 'sim-super-data-report', '_n_sim_super_data_reports');
//	add_submenu_page('edit.php?post_type=product', 'Lấy ID', 'Lấy ID', 'manage_options', 'get-product-ids', '_n_get_product_ids');
}

add_action('admin_menu', '_n_admin_menus');

/**
 * Lấy ID sản phẩm
 *
 * @since 0.0.1
 */
function _n_get_product_ids(){
	require_once N_CHILD_DIR . '/lib/admin/views/get-ids.php';
}

/**
 * Sim importer
 *
 * @since 0.0.1
 */
function _n_sim_importer(){
	require_once N_CHILD_DIR . '/lib/admin/views/sim-importer.php';
}

/**
 * Sim super data importer
 *
 * @since 0.0.1
 */
function _n_sim_super_data_importer(){
	require_once N_CHILD_DIR . '/lib/admin/views/sim-super-data-importer.php';
}

/**
 * Sim super data importer
 *
 * @since 0.0.1
 */
function _n_sim_sold_out_importer(){
	require_once N_CHILD_DIR . '/lib/admin/views/sim-sold-out-importer.php';
}

/**
 * Package importer
 *
 * @since 0.0.1
 */
function _n_package_importer(){
	require_once N_CHILD_DIR . '/lib/admin/views/package-importer.php';
}

/**
 * Sim API importer
 *
 * @since 0.0.1
 */
function _n_sim_api_importer(){
	require_once N_CHILD_DIR . '/lib/admin/views/api-importer.php';
}

/**
 * Sim reports
 *
 * @since 0.0.1
 */
function _n_sim_reports(){
	require_once N_CHILD_DIR . '/lib/admin/views/sim-reports.php';
}

/**
 * Sim super data reports
 *
 * @since 0.0.1
 */
function _n_sim_super_data_reports(){
	require_once N_CHILD_DIR . '/lib/admin/views/sim-super-data-reports.php';
}

/**
 * Sim import history
 *
 * @since 0.0.1
 */
function _n_import_history(){
	require_once N_CHILD_DIR . '/lib/admin/views/import-history.php';
}
