<?php
/**
 * N Framework
 *
 * WARNING: This file is part of the core N Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @since      0.0.1
 * @package    N
 * @subpackage N/lib/functions
 */

if (!defined('ABSPATH')):
	exit; // Exit if accessed directly.
endif;

/**
 * Đăng nhập API
 */
function _n_api_login(){
	$username = 'api_taiphat';
	$password = 'tp#2023#Qcf9vFuEsz';
	$url      = 'http://api-appchonso.osp.vn/api/v2/users/login';

	$headers = [
		'Content-Type' => 'application/json',
	];

	$body = [
		"username" => $username,
		"password" => $password
	];

	$response = wp_remote_post($url, [
		'headers' => $headers,
		'body'    => json_encode($body)
	]);

	if (is_wp_error($response)):
		return $response->get_error_message();
	else:
		return json_decode(wp_remote_retrieve_body($response));
	endif;
}

function _n_api_search_filter(){
	$login_data   = _n_api_login();
	$access_token = $login_data->data->accessTokenInfo->accessToken;
	$url          = 'http://api-appchonso.osp.vn/api/v2/catalog/searchFilter';

	$headers = [
		'Content-Type'  => 'application/json',
		'Authorization' => 'Bearer ' . $access_token,
	];

	$body = [
		"srcReq" => "APPCS"
	];

	$response = wp_remote_post($url, [
		'headers' => $headers,
		'body'    => json_encode($body)
	]);

	if (is_wp_error($response)):
		return $response->get_error_message();
	else:
		return json_decode(wp_remote_retrieve_body($response));
	endif;
}

function _n_api_msisdn_detail($phone){
	$login_data   = _n_api_login();
	$access_token = $login_data->data->accessTokenInfo->accessToken;
	$url          = 'http://api-appchonso.osp.vn/api/v2/stock/msisdnDetail';

	$headers = [
		'Content-Type'  => 'application/json',
		'Authorization' => 'Bearer ' . $access_token,
	];

	$body = [
		"msisdn" => $phone
	];

	$response = wp_remote_post($url, [
		'headers' => $headers,
		'body'    => json_encode($body)
	]);

	if (is_wp_error($response)):
		return $response->get_error_message();
	else:
		return json_decode(wp_remote_retrieve_body($response));
	endif;
}

function _n_api_filter_msisdn($args = []){
	$defaults = [
		"avoids"       => [],
		"groupMsisdns" => [],
		"page"         => 1,
		"preNumbers"   => [],
		"regions"      => [],
		"sizeOfPage"   => 10,
		"srcStrs"      => [],
		"statuss"      => [0],
		"types"        => [],
	];

	$body = wp_parse_args($args, $defaults);

	$login_data   = _n_api_login();
	$access_token = $login_data->data->accessTokenInfo->accessToken;
	$url          = 'http://api-appchonso.osp.vn/api/v2/stock/filterMsisdn';

	$headers = [
		'Content-Type'  => 'application/json',
		'Authorization' => 'Bearer ' . $access_token,
	];

	$response = wp_remote_post($url, [
		'headers' => $headers,
		'body'    => json_encode($body)
	]);

	if (is_wp_error($response)):
		return $response->get_error_message();
	else:
		return json_decode(wp_remote_retrieve_body($response));
	endif;
}
