<?php
/**
 * N Framework
 *
 * WARNING: This file is part of the core N Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @since      0.0.1
 * @package    N
 * @subpackage N/lib/functions
 */

if (!defined('ABSPATH')):
	exit; // Exit if accessed directly.
endif;

/**
 * Enqueue scripts and styles.
 *
 * @since    0.0.1
 */
function _n_load_scripts(){
	$theme_version = wp_get_theme()->get('Version');

	// Include jquery
	wp_enqueue_script('jquery');

	if ((!is_admin()) && is_singular() && comments_open() && get_option('thread_comments')):
		wp_enqueue_script('comment-reply');
	endif;

	wp_enqueue_style('_n-bootstrap', get_theme_file_uri('assets/libs/bootstrap/css/bootstrap.min.css'), [], $theme_version, 'all');
	wp_enqueue_style('_n-mmenu', get_theme_file_uri('assets/libs/mmenu/mmenu.css'), [], $theme_version, 'all');
	wp_enqueue_style('_n-leaflet', get_theme_file_uri('assets/css/leaflet.css'), [], $theme_version, 'all');
	wp_enqueue_style('_n-select2', get_theme_file_uri('assets/libs/select2/select2.min.css'), [], $theme_version, 'all');
	wp_enqueue_style('_n-slick', get_theme_file_uri('assets/libs/slick/slick.css'), [], $theme_version, 'all');
	wp_enqueue_style('_n-font-awesome', get_theme_file_uri('assets/libs/font-awesome/css/all.min.css'), [], $theme_version, 'all');
	wp_enqueue_style('_n-framework', get_theme_file_uri('assets/css/style.css'), [], $theme_version, 'all');

	wp_enqueue_script('_n-bootstrap', get_theme_file_uri('assets/libs/bootstrap/js/bootstrap.bundle.min.js'), [], $theme_version, true);
	wp_enqueue_script('_n-mmenu', get_theme_file_uri('assets/libs/mmenu/mmenu.js'), ['jquery'], $theme_version, true);
	wp_enqueue_script('_n-highlight', get_theme_file_uri('assets/js/jquery.highlight-4.js'), ['jquery'], $theme_version, true);
	wp_enqueue_script('_n-leaflet', get_theme_file_uri('assets/js/leaflet.js'), [], $theme_version, true);
	wp_enqueue_script('_n-select2', get_theme_file_uri('assets/libs/select2/select2.min.js'), [], $theme_version, true);
	wp_enqueue_script('_n-slick', get_theme_file_uri('assets/libs/slick/slick.js'), [], $theme_version, true);
	wp_enqueue_script('_n-tata', get_theme_file_uri('assets/libs/tata/tata.js'), [], $theme_version, true);
	wp_enqueue_script('_n-framework', get_theme_file_uri('assets/js/scripts.js'), ['jquery'], $theme_version, true);
	wp_localize_script('_n-framework', '_n_framework', [
		'admin_ajax_url' => admin_url('admin-ajax.php'),
	]);
}

add_action('wp_enqueue_scripts', '_n_load_scripts');
