<?php
/**
 * N Framework
 *
 * WARNING: This file is part of the core N Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @since      0.0.1
 * @package    N
 * @subpackage N/lib/functions
 */

if (!defined('ABSPATH')):
	exit; // Exit if accessed directly.
endif;

/**
 * Đặt hàng
 */
function _n_sim_order(){
	$product_sim        = isset($_POST['product_sim']) ? intval($_POST['product_sim']) : 0;
	$product_data       = isset($_POST['product_data']) ? intval($_POST['product_data']) : 0;
	$product_quantity   = isset($_POST['product_quantity']) ? intval($_POST['product_quantity']) : 1;
	$general_settings   = get_field('_theme_general_settings', 'option');
	$customer_info_page = $general_settings['_customer_info_page'];
	$fee                = $general_settings['_fee'];
	$hoa_mang           = $fee['_phi_hoa_mang'];
	$van_chuyen         = $fee['_phi_van_chuyen'];
	$discount           = $general_settings['_discount'];
	$discount_amount    = $discount['_discount_amount'];
	$discount_type      = $discount['_discount_type'];
	$loai_sim           = get_post_meta($product_sim, '_loai_sim', true);
	$nha_mang           = get_post_meta($product_sim, '_nha_mang', true);
	$nha_cung_cap       = get_post_meta($product_sim, '_nha_cung_cap', true);

	// tạo đơn hàng
	$order    = wc_create_order();
	$order_id = $order->get_id();

	if ($product_sim != 0):
		$sim = wc_get_product($product_sim);
		$order->add_product(wc_get_product($sim), $product_quantity);
		update_post_meta($order_id, '_sim_id', $product_sim);

		if ($loai_sim != ''):
			update_post_meta($order_id, '_loai_sim', $loai_sim);
		endif;

		if ($nha_mang != ''):
			update_post_meta($order_id, '_nha_mang', $nha_mang);
		endif;

		if ($nha_cung_cap != ''):
			update_post_meta($order_id, '_nha_cung_cap', $nha_cung_cap);
		endif;
	endif;

	if ($product_data != 0):
		$package = wc_get_product($product_data);
		$order->add_product($package, 1);
		update_post_meta($order_id, '_package_id', $product_data);
	endif;

	if ((float) $van_chuyen > 0):
		$fee = new WC_Order_Item_Fee();
		$fee->set_name('Phí vận chuyển');
		$fee->set_amount($van_chuyen);
		$fee->set_total($van_chuyen);
		$order->add_item($fee);
	endif;

	if ($loai_sim == '_tra_sau'):
		$fee = new WC_Order_Item_Fee();
		$fee->set_name('Phí hoà mạng');
		$fee->set_amount($hoa_mang);
		$fee->set_total($hoa_mang);
		$order->add_item($fee);
	endif;

	if ($discount_amount != ''):
		$product   = wc_get_product($product_sim);
		$sim_price = (float) $product->get_price();

		if ($discount_type == 'percent'):
			$cart_total_val = $sim_price - ($discount_amount * $sim_price / 100);
		else:
			$cart_total_val = $sim_price - (float) $discount_amount;
		endif;

		$discount = $sim_price - $cart_total_val;

		$fee = new WC_Order_Item_Fee();
		$fee->set_name('Giảm giá');
		$fee->set_amount(- $discount);
		$fee->set_total(- $discount);
		$order->add_item($fee);
	endif;

	// Tiếp thị liên kết
	if (isset($_COOKIE['refcode'])):
		$aff_id = $_COOKIE['refcode'];
		update_post_meta($order_id, '_refcode', $aff_id);
	endif;

	// trạng thái đơn hàng
	$order->set_status('processing');
	$order->calculate_totals();
	$order->save();

	wp_send_json_success([
		'order'   => $order_id,
		'url'     => wp_nonce_url($customer_info_page, 'customer_info') . '&order_id=' . $order_id,
		'message' => __('Thanh toán thành công'),
	]);

	wp_die();
}

add_action('wp_ajax_sim_order', '_n_sim_order');
add_action('wp_ajax_nopriv_sim_order', '_n_sim_order');

/**
 * Cập nhật thông tin khách hàng
 */
function _n_update_customer_info(){
	$general_settings    = get_field('_theme_general_settings', 'option');
	$complete_page       = $general_settings['_complete_page'];
	$owner_register_page = $general_settings['_owner_register_page'];
	$name                = isset($_POST['name']) ? esc_attr($_POST['name']) : '';
	$phone               = isset($_POST['phone']) ? esc_attr($_POST['phone']) : '';
	$delivery_method     = isset($_POST['delivery-method']) ? esc_attr($_POST['delivery-method']) : '';
	$branch              = isset($_POST['branch']) ? esc_attr($_POST['branch']) : '';
	$owner               = isset($_POST['owner']) ? esc_attr($_POST['owner']) : '';
	$note                = isset($_POST['note']) ? esc_attr($_POST['note']) : '';
	$province            = isset($_POST['province']) ? esc_attr($_POST['province']) : '';
	$district            = isset($_POST['district']) ? esc_attr($_POST['district']) : '';
	$wards               = isset($_POST['wards']) ? esc_attr($_POST['wards']) : '';
	$address             = isset($_POST['address']) ? esc_attr($_POST['address']) : '';
	$order_id            = isset($_POST['order']) ? esc_attr($_POST['order']) : '';
	$province_result     = [];
	$district_result     = [];
	$wards_result        = [];
	$telegram_data       = [];

	if ($name == ''):
		wp_send_json_error('Họ và tên không được để trống');
	endif;

	if ($phone == ''):
		wp_send_json_error('Bạn chưa nhập Số điện thoại');
	elseif (!preg_match("/^(0|\+84)(\s|\.)?((3[2-9])|(5[689])|(7[06-9])|(8[1-689])|(9[0-46-9]))(\d)(\s|\.)?(\d{3})(\s|\.)?(\d{3})$/", $phone)):
		wp_send_json_error('Số điện thoại không hợp lệ');
	endif;

	if ($delivery_method == 'delivery-method-1'):
		if ($branch == ''):
			wp_send_json_error('Vui lòng chọn chi nhánh lấy hàng');
		endif;
	else:
		if ($province == ''):
			wp_send_json_error('Bạn chưa chọn Tỉnh/thành phố');
		endif;

		if ($district == ''):
			wp_send_json_error('Bạn chưa chọn Quận huyện');
		endif;

		if ($wards == ''):
			wp_send_json_error('Bạn chưa chọn Xã/Phường/Thị trấn');
		endif;

		if ($address == ''):
			wp_send_json_error('Bạn chưa nhập địa chỉ');
		endif;
	endif;

	$province_args = _n_get_config('province');
	$district_args = _n_get_config('district');
	$wards_args    = _n_get_config('wards');

	if ($province != ''):
		$province_result = array_filter($province_args, function ($item){
			return $item["code"] === $_POST['province'];
		});
	endif;

	if ($district != ''):
		$district_result = array_filter($district_args, function ($item){
			return $item["code"] === $_POST['district'];
		});
	endif;

	if ($wards != ''):
		$wards_result = array_filter($wards_args, function ($item){
			return $item["code"] === $_POST['wards'];
		});
	endif;

	$province_item = reset($province_result)['name'];
	$district_item = reset($district_result)['name'];
	$wards_item    = reset($wards_result)['name'];

	$full_address = $address . ', ' . $wards_item . ', ' . $district_item . ', ' . $province_item;

	if ($delivery_method == 'delivery-method-1'):
		$delivery = 'Nhận hàng tại ' . $branch;
		update_post_meta($order_id, '_branch', $branch);
	else:
		$delivery = 'Giao hàng tận nhà: ' . $full_address;
	endif;

	update_post_meta($order_id, '_shipping_first_name', $name);
	update_post_meta($order_id, '_shipping_phone', $phone);
	update_post_meta($order_id, '_shipping_state', $province_item);
	update_post_meta($order_id, '_shipping_city', $district_item);
	update_post_meta($order_id, '_shipping_address_1', $address);
	update_post_meta($order_id, '_shipping_address_2', $wards_item);

	update_post_meta($order_id, '_billing_first_name', $name);
	update_post_meta($order_id, '_billing_phone', $phone);
	update_post_meta($order_id, '_billing_state', $province_item);
	update_post_meta($order_id, '_billing_city', $district_item);
	update_post_meta($order_id, '_billing_address_1', $address);
	update_post_meta($order_id, '_billing_address_2', $wards_item);

	$order = wc_get_order($order_id);

	$order->add_order_note($delivery);

	if ($note != ''):
		$order->add_order_note('Khách hàng ghi chú: ' . $note);
	endif;

	$refcode = "";
	if (isset($_COOKIE['refcode'])):
		$refcode = $_COOKIE['refcode'];
	endif;

	$sim_id              = get_post_meta($order_id, '_sim_id', true);
	$nha_cung_cap        = get_post_meta($sim_id, '_nha_cung_cap', true);
	$nha_cung_cap_config = _n_get_config('nha-cung-cap');
	$product             = wc_get_product($sim_id);

	$telegram_data['refCode']       = $refcode;
	$telegram_data['customerName']  = $name;
	$telegram_data['customerPhone'] = $phone;
	$telegram_data['address']       = $delivery;
	$telegram_data['buySim']        = get_the_title($sim_id);
	$telegram_data['requiredCode']  = get_the_title(get_post_meta($order_id, '_package_id', true));
	$telegram_data['simType']       = get_post_meta($order_id, '_sim_type', true);
	$telegram_data['supplierName']  = $nha_cung_cap_config[$nha_cung_cap]['name'];
	$telegram_data['simPrice']      = $product->get_price();;

	_n_send_telegram_message($telegram_data);

	if ($owner == 'yes'):
		$order->add_order_note('Khách hàng muốn đăng ký chính chủ');
		$order->save();
		wp_send_json_success([
			'telegram_data' => $telegram_data,
			'order'         => $order_id,
			'url'           => wp_nonce_url($owner_register_page, 'owner_register') . '&order_id=' . $order_id,
			'message'       => __('Đăng ký chính chủ', 'sim'),
		]);
	else:
		$order->save();
		wp_send_json_success([
			'telegram_data' => $telegram_data,
			'order'         => $order_id,
			'url'           => wp_nonce_url($complete_page, 'complete') . '&order_id=' . $order_id,
			'message'       => __('Đặt hàng thành công', 'sim'),
		]);
	endif;

	wp_die();
}

add_action('wp_ajax_customer_info', '_n_update_customer_info');
add_action('wp_ajax_nopriv_customer_info', '_n_update_customer_info');

/**
 * Đăng ký chính chủ
 */
function _n_owner_register(){
	$order_id         = isset($_POST['order']) ? esc_attr($_POST['order']) : '';
	$general_settings = get_field('_theme_general_settings', 'option');
	$complete_page    = $general_settings['_complete_page'];

	if ($order_id == ''):
		wp_send_json_error('Order not found');
	endif;

	$id_front   = isset($_FILES['id_front']) ? $_FILES['id_front'] : '';
	$id_back    = isset($_FILES['id_back']) ? $_FILES['id_back'] : '';
	$portrait   = isset($_FILES['id_back']) ? $_FILES['portrait'] : '';
	$short_clip = isset($_FILES['short_clip']) ? $_FILES['short_clip'] : '';

	if ($id_front['name'] == ''):
		wp_send_json_error('Vui lòng thêm CMND/CCCD mặt trước');
	endif;

	if ($id_back['name'] == ''):
		wp_send_json_error('Vui lòng thêm CMND/CCCD mặt sau');
	endif;

	if ($portrait['name'] == ''):
		wp_send_json_error('Vui lòng thêm ảnh chân dung');
	endif;

	if ($short_clip['name'] == ''):
		wp_send_json_error('Vui lòng thêm clip ngắn');
	endif;

	if ($id_front['name'] != ''):
		$id_front_file = [
			'name'     => $id_front['name'],
			'type'     => $id_front['type'],
			'tmp_name' => $id_front['tmp_name'],
			'error'    => $id_front['error'],
			'size'     => $id_front['size']
		];

		$attach_id = _n_upload_user_file($id_front_file);
		update_post_meta($order_id, '_id_card_front', $attach_id);
	endif;

	if ($id_back['name'] != ''):
		$id_back_file = [
			'name'     => $id_back['name'],
			'type'     => $id_back['type'],
			'tmp_name' => $id_back['tmp_name'],
			'error'    => $id_back['error'],
			'size'     => $id_back['size']
		];

		$attach_id = _n_upload_user_file($id_back_file);
		update_post_meta($order_id, '_id_card_back', $attach_id);
	endif;

	if ($portrait['name'] != ''):
		$portrait_file = [
			'name'     => $portrait['name'],
			'type'     => $portrait['type'],
			'tmp_name' => $portrait['tmp_name'],
			'error'    => $portrait['error'],
			'size'     => $portrait['size']
		];

		$attach_id = _n_upload_user_file($portrait_file);
		update_post_meta($order_id, '_avatar', $attach_id);
	endif;

	if ($short_clip['name'] != ''):
		$short_clip_file = [
			'name'     => $short_clip['name'],
			'type'     => $short_clip['type'],
			'tmp_name' => $short_clip['tmp_name'],
			'error'    => $short_clip['error'],
			'size'     => $short_clip['size']
		];

		$attach_id = _n_upload_user_file($short_clip_file);
		update_post_meta($order_id, '_short_clip', $attach_id);
	endif;

	wp_send_json_success([
		'order'   => $order_id,
		'url'     => wp_nonce_url($complete_page, 'complete') . '&order_id=' . $order_id,
		'message' => __('Đặt hàng thành công', 'sim'),
	]);

	wp_die();
}

add_action('wp_ajax_owner_register', '_n_owner_register');
add_action('wp_ajax_nopriv_owner_register', '_n_owner_register');

/**
 * Lấy Quận huyện
 */
function _n_get_district(){
	$options_html = '<option value="" selected>Vui lòng chọn</option>';
	$province     = isset($_POST['province']) ? esc_attr($_POST['province']) : '';
	$grouped_data = [];

	foreach (_n_get_config('district') as $item):
		$parent_code = $item['parent_code'];
		$code        = $item['code'];
		$name        = $item['name'];

		if (!isset($grouped_data[$parent_code])):
			$grouped_data[$parent_code] = [];
		endif;

		$grouped_data[$parent_code][] = ['name' => $name, 'code' => $code];
	endforeach;


	if ($grouped_data[$province]):
		foreach ($grouped_data[$province] as $province):
			$options_html .= '<option value="' . $province['code'] . '">' . $province['name'] . '</option>';
		endforeach;
	endif;

	echo $options_html;

	wp_die();
}

add_action('wp_ajax_get_district', '_n_get_district');
add_action('wp_ajax_nopriv_get_district', '_n_get_district');

/**
 * Lấy phường xã
 */
function _n_get_wards(){
	$options_html = '<option value="" selected>Vui lòng chọn</option>';
	$district     = isset($_POST['district']) ? esc_attr($_POST['district']) : '';
	$grouped_data = [];

	foreach (_n_get_config('wards') as $item):
		$parent_code = $item['parent_code'];
		$code        = $item['code'];
		$name        = $item['name'];

		if (!isset($grouped_data[$parent_code])):
			$grouped_data[$parent_code] = [];
		endif;

		$grouped_data[$parent_code][] = ['name' => $name, 'code' => $code];
	endforeach;


	if ($grouped_data[$district]):
		foreach ($grouped_data[$district] as $province):
			$options_html .= '<option value="' . $province['code'] . '">' . $province['name'] . '</option>';
		endforeach;
	endif;

	echo $options_html;

	wp_die();
}

add_action('wp_ajax_get_wards', '_n_get_wards');
add_action('wp_ajax_nopriv_get_wards', '_n_get_wards');
